package recipes

import (
	"bytes"
	"image"
	"image/color"
	"image/png"
)

func pwaRecipe() Recipe {
	return Recipe{
		Name: "pwa",
		Summary: map[string]string{
			"en": "installable app manifest, icons and a browser-aware install invitation",
			"pt": "manifesto, ícones e convite de instalação que entende o navegador",
		},
		Doc: "/recipes/pwa",
		Files: []File{
			{Rel: "public/manifest.webmanifest", Body: pwaManifest},
			{Rel: "public/icon-192.png", Data: pwaIcon(192)},
			{Rel: "public/icon-512.png", Data: pwaIcon(512)},
			{Rel: "public/pwa.js", Body: pwaScript},
			{Rel: "internal/pwa/invite.go", Go: true, Body: pwaInvite},
			{Rel: "{{.At}}install/page.go", Go: true, Body: pwaPage},
		},
		Next: map[string]string{
			"en": "Replace public/icon-192.png and public/icon-512.png with the application's icons, run `trilha gen`, then open {{.URL}}install. The recipe deliberately adds no service worker: offline caching is a product decision.",
			"pt": "Troque public/icon-192.png e public/icon-512.png pelos ícones da aplicação, rode `trilha gen` e abra {{.URL}}install. A receita não cria service worker de propósito: cache offline é decisão do produto.",
		},
	}
}

func pwaIcon(size int) []byte {
	img := image.NewRGBA(image.Rect(0, 0, size, size))
	background := color.RGBA{R: 24, G: 24, B: 27, A: 255}
	foreground := color.RGBA{R: 250, G: 250, B: 250, A: 255}
	for y := 0; y < size; y++ {
		for x := 0; x < size; x++ {
			pixel := background
			if x > size/4 && x < 3*size/4 && y > size/4 && y < 3*size/4 {
				pixel = foreground
			}
			img.SetRGBA(x, y, pixel)
		}
	}
	var out bytes.Buffer
	if err := png.Encode(&out, img); err != nil {
		panic(err)
	}
	return out.Bytes()
}

const pwaManifest = `{
  "name": "{{.Name}}",
  "short_name": "{{.Name}}",
  "start_url": "/",
  "display": "standalone",
  "background_color": "#18181b",
  "theme_color": "#18181b",
  "icons": [
    {"src": "/icon-192.png", "sizes": "192x192", "type": "image/png"},
    {"src": "/icon-512.png", "sizes": "512x512", "type": "image/png"}
  ]
}
`

const pwaScript = `(() => {
  "use strict";
  const roots = [...document.querySelectorAll("[data-ui-install-app]")];
  if (!roots.length) return;
  const manifest = roots[0].getAttribute("data-ui-install-manifest");
  if (manifest && !document.querySelector('link[rel="manifest"]')) {
    const link = document.createElement("link");
    link.rel = "manifest";
    link.href = manifest;
    document.head.appendChild(link);
  }
  const standalone = navigator.standalone === true || matchMedia("(display-mode: standalone)").matches;
  const ios = /iPad|iPhone|iPod/.test(navigator.userAgent);
  const safari = /Safari/.test(navigator.userAgent) && !/CriOS|FxiOS|EdgiOS/.test(navigator.userAgent);
  const hide = (root) => root.remove();
  const show = (root, selector) => {
    root.querySelectorAll("[data-ui-install-fallback],[data-ui-install-ios],[data-ui-install-ios-other]").forEach((node) => node.hidden = true);
    const node = root.querySelector(selector);
    if (node) node.hidden = false;
  };
  if (standalone) {
    document.cookie = "trilha_standalone=1; Path=/; Max-Age=31536000; SameSite=Lax";
    roots.forEach(hide);
    return;
  }
  roots.forEach((root) => {
    if (ios) show(root, safari ? "[data-ui-install-ios]" : "[data-ui-install-ios-other]");
    else show(root, "[data-ui-install-fallback]");
  });
  let deferred;
  addEventListener("beforeinstallprompt", (event) => {
    event.preventDefault();
    deferred = event;
    roots.forEach((root) => {
      show(root, "[data-ui-install-button]");
      const button = root.querySelector("[data-ui-install-button]");
      if (button) button.onclick = async () => {
        await deferred.prompt();
        const choice = await deferred.userChoice;
        deferred = null;
        if (choice.outcome === "accepted") roots.forEach(hide);
      };
    });
  });
  addEventListener("appinstalled", () => {
    document.cookie = "trilha_standalone=1; Path=/; Max-Age=31536000; SameSite=Lax";
    roots.forEach(hide);
  });
})();
`

const pwaInvite = `// Package pwa owns the install invitation generated by trilha add pwa.
package pwa

import (
	"github.com/emersonjoe/trilha"
	"github.com/emersonjoe/trilha/h"
	"github.com/emersonjoe/trilha/ui"
)

// Invite is the browser-aware install invitation. The JavaScript hides it
// when the app is already installed, offers the native prompt where browsers
// expose it, and explains the Safari steps on iPhone and iPad.
func Invite(c *trilha.Ctx) h.Node {
	return ui.InstallApp(c, ui.InstallAppOpts{
		Help: "/install",
	})
}
`

const pwaPage = `package install

import (
	"github.com/emersonjoe/trilha"
	"github.com/emersonjoe/trilha/h"
	"github.com/emersonjoe/trilha/ui"

	"{{.Module}}/internal/pwa"
)

func Page(c *trilha.Ctx) (h.Node, error) {
	c.SetTitle("{{if eq .Lang "pt"}}Instalar app{{else}}Install app{{end}}")
	return ui.Container(
		h.H1(h.Text("{{if eq .Lang "pt"}}Instalar app{{else}}Install app{{end}}")),
		h.P(h.Text("{{if eq .Lang "pt"}}Instale para abrir pela tela inicial e usar em uma janela própria. No iPhone e iPad, faça isso pelo Safari.{{else}}Install it to open from the home screen in its own window. On iPhone and iPad, do this in Safari.{{end}}")),
		pwa.Invite(c),
	), nil
}
`
