package recipes

// words is the text the recipes write into the project, per language.
//
// It is a table and not a translation mechanism, which is the same trade the
// rest of the scaffold makes: what comes out is a file somebody owns and
// edits, so a third language is a find-and-replace in their own code rather
// than a feature of ours.
var words = func(lang string) map[string]string {
	if lang == "pt" {
		return map[string]string{
			"audit_title": "Auditoria",
			"audit_desc":  "Quem fez o quê, em quê, e de onde.",

			"settings_title":        "Configurações",
			"settings_saved":        "Configurações salvas.",
			"settings_name":         "Nome da aplicação",
			"settings_support":      "E-mail de suporte",
			"settings_days":         "Dias até expirar",
			"settings_default_name": "Minha aplicação",

			"keys_title":     "Chaves de API",
			"keys_desc":      "A chave aparece uma vez, quando é criada. O que fica guardado é o hash dela.",
			"keys_name":      "Nome",
			"keys_scopes":    "Escopos",
			"keys_create":    "Criar chave",
			"keys_created":   "Chave criada. Copie agora.",
			"keys_revoked":   "Chave revogada.",
			"keys_need_name": "dê um nome à chave: é por ele que alguém vai saber qual revogar",

			"login_title":    "Entrar",
			"login_email":    "E-mail",
			"login_password": "Senha",
			"login_wrong":    "E-mail ou senha inválidos.",
			"login_empty":    "Ninguém pode entrar ainda: defina ADMIN_EMAIL e ADMIN_PASSWORD e reinicie.",

			"users_title":       "Usuários",
			"users_desc":        "Quem entra, com qual papel. Convidar cria a pessoa sem senha: quem a define é ela, no link.",
			"users_email":       "E-mail",
			"users_name":        "Nome",
			"users_role":        "Papel",
			"users_state":       "Estado",
			"users_created":     "Criado",
			"users_active":      "ativo",
			"users_inactive":    "inativo",
			"users_invite":      "Convidar",
			"users_invited":     "Convite criado. O link vale 48 horas.",
			"users_invite_link": "Link do convite",
			"users_need_email":  "diga o e-mail de quem você está convidando",
			"users_save":        "Salvar",
			"users_activate":    "Ativar",
			"users_deactivate":  "Desativar",
			"users_reset":       "Resetar senha",
			"users_reset_ask":   "Resetar a senha desta pessoa?",
			"users_reset_desc":  "A senha atual para de valer e um link novo é emitido.",
			"users_reset_done":  "Link novo emitido. O anterior parou de valer.",
			"users_none":        "Ninguém aqui ainda.",

			"invite_title":    "Defina sua senha",
			"invite_password": "Senha",
			"invite_submit":   "Salvar e entrar",
			"invite_invalid":  "Este convite não vale mais.",
			"invite_short":    "A senha precisa de pelo menos 12 caracteres.",

			"perms_title": "Permissões",
			"perms_desc":  "Um papel por linha, um módulo por coluna. Sem JavaScript.",
			"perms_none":  "sem acesso",
			"perms_save":  "Salvar",
			"perms_saved": "Permissões salvas.",

			"profile_title":         "Minha conta",
			"profile_name":          "Nome",
			"profile_save":          "Salvar",
			"profile_saved":         "Nome salvo.",
			"profile_need_name":     "Diga um nome.",
			"profile_password":      "Senha",
			"profile_password_desc": "Trocar a senha fecha esta sessão: entre de novo com a nova.",
			"profile_current":       "Senha atual",
			"profile_new":           "Senha nova",
			"profile_change":        "Trocar senha",
			"profile_wrong":         "A senha atual não confere, ou a nova tem menos de 12 caracteres.",
			"profile_password_done": "Senha trocada. Entre de novo.",
			"profile_gone":          "Sua sessão acabou.",

			"hooks_title": "Webhooks",
			"hooks_desc":  "O que este app avisa para fora. A entrega sai fora da requisição, assinada, e tenta de novo quando o outro lado está fora do ar.",
		}
	}
	return map[string]string{
		"audit_title": "Audit trail",
		"audit_desc":  "Who did what, to what, and from where.",

		"settings_title":        "Settings",
		"settings_saved":        "Settings saved.",
		"settings_name":         "Application name",
		"settings_support":      "Support e-mail",
		"settings_days":         "Days before expiry",
		"settings_default_name": "My application",

		"keys_title":     "API keys",
		"keys_desc":      "A key is shown once, when it is created. What is stored is its hash.",
		"keys_name":      "Name",
		"keys_scopes":    "Scopes",
		"keys_create":    "Create key",
		"keys_created":   "Key created. Copy it now.",
		"keys_revoked":   "Key revoked.",
		"keys_need_name": "give the key a name: it is how somebody later knows which one to revoke",

		"login_title":    "Sign in",
		"login_email":    "E-mail",
		"login_password": "Password",
		"login_wrong":    "Wrong e-mail or password.",
		"login_empty":    "Nobody can sign in yet: set ADMIN_EMAIL and ADMIN_PASSWORD and restart.",

		"users_title":       "Users",
		"users_desc":        "Who gets in, with what role. Inviting creates the person with no password: they set it, from the link.",
		"users_email":       "E-mail",
		"users_name":        "Name",
		"users_role":        "Role",
		"users_state":       "State",
		"users_created":     "Created",
		"users_active":      "active",
		"users_inactive":    "inactive",
		"users_invite":      "Invite",
		"users_invited":     "Invitation created. The link is worth 48 hours.",
		"users_invite_link": "Invitation link",
		"users_need_email":  "say the e-mail of whoever you are inviting",
		"users_save":        "Save",
		"users_activate":    "Activate",
		"users_deactivate":  "Deactivate",
		"users_reset":       "Reset password",
		"users_reset_ask":   "Reset this person's password?",
		"users_reset_desc":  "The current password stops working and a new link is issued.",
		"users_reset_done":  "New link issued. The previous one stopped working.",
		"users_none":        "Nobody here yet.",

		"invite_title":    "Set your password",
		"invite_password": "Password",
		"invite_submit":   "Save and sign in",
		"invite_invalid":  "This invitation is no longer valid.",
		"invite_short":    "The password needs at least 12 characters.",

		"perms_title": "Permissions",
		"perms_desc":  "A role per row, a module per column. No JavaScript.",
		"perms_none":  "no access",
		"perms_save":  "Save",
		"perms_saved": "Permissions saved.",

		"profile_title":         "My account",
		"profile_name":          "Name",
		"profile_save":          "Save",
		"profile_saved":         "Name saved.",
		"profile_need_name":     "Say a name.",
		"profile_password":      "Password",
		"profile_password_desc": "Changing the password ends this session: sign in again with the new one.",
		"profile_current":       "Current password",
		"profile_new":           "New password",
		"profile_change":        "Change password",
		"profile_wrong":         "The current password does not match, or the new one is shorter than 12 characters.",
		"profile_password_done": "Password changed. Sign in again.",
		"profile_gone":          "Your session ended.",

		"hooks_title": "Webhooks",
		"hooks_desc":  "What this application announces to the outside. The delivery leaves outside the request, signed, and tries again when the other side is down.",
	}
}
