package recipes

// platformWordsEN is the text of the platform recipes (spec 162): billing,
// notify and admin. A table of its own so the three recipes read as one
// block, merged into words by language like the rest.
func platformWordsEN() map[string]string {
	return map[string]string{
		"billing_title":                 "Billing",
		"billing_desc":                  "Subscriptions by state. The provider charges the card; this application decides what each event means.",
		"billing_plans":                 "Plans",
		"billing_invoices":              "Invoices",
		"billing_customer":              "Customer",
		"billing_plan":                  "Plan",
		"billing_subscription":          "Subscription",
		"billing_state":                 "State",
		"billing_attempts":              "Failed charges",
		"billing_all":                   "All states",
		"billing_empty":                 "No subscriptions yet.",
		"billing_search":                "Search by e-mail",
		"billing_plan_name":             "Name",
		"billing_plan_cents":            "Price (cents)",
		"billing_plan_currency":         "Currency",
		"billing_plan_interval":         "Interval",
		"billing_plan_month":            "Monthly",
		"billing_plan_year":             "Yearly",
		"billing_plan_save":             "Create plan",
		"billing_plan_delete":           "Delete",
		"billing_plans_empty":           "No plans yet.",
		"billing_plan_in_use":           "A subscription still uses this plan.",
		"billing_invoice":               "Invoice",
		"billing_amount":                "Amount",
		"billing_issued":                "Issued",
		"billing_paid":                  "Paid",
		"billing_open":                  "Open",
		"billing_invoices_empty":        "No invoices yet.",
		"billing_csv":                   "Export CSV",
		"billing_state_trial":           "Trial",
		"billing_state_active":          "Active",
		"billing_state_past_due":        "Past due",
		"billing_state_canceled":        "Canceled",
		"billing_mail_failed_subject":   "Your payment did not go through",
		"billing_mail_failed_body":      "We could not charge your subscription. We will try again; after the third failed charge the subscription is canceled.",
		"billing_mail_canceled_subject": "Your subscription was canceled",
		"billing_mail_canceled_body":    "After three failed charges the subscription was canceled. You can subscribe again whenever you want.",
	}
}

// platformWordsPT is the Portuguese table of the platform recipes.
func platformWordsPT() map[string]string {
	return map[string]string{
		"billing_title":                 "Cobrança",
		"billing_desc":                  "Assinaturas por estado. O provedor cobra o cartão; este app decide o que cada evento significa.",
		"billing_plans":                 "Planos",
		"billing_invoices":              "Faturas",
		"billing_customer":              "Cliente",
		"billing_plan":                  "Plano",
		"billing_subscription":          "Assinatura",
		"billing_state":                 "Estado",
		"billing_attempts":              "Cobranças falhas",
		"billing_all":                   "Todos os estados",
		"billing_empty":                 "Nenhuma assinatura ainda.",
		"billing_search":                "Buscar por e-mail",
		"billing_plan_name":             "Nome",
		"billing_plan_cents":            "Preço (centavos)",
		"billing_plan_currency":         "Moeda",
		"billing_plan_interval":         "Intervalo",
		"billing_plan_month":            "Mensal",
		"billing_plan_year":             "Anual",
		"billing_plan_save":             "Criar plano",
		"billing_plan_delete":           "Apagar",
		"billing_plans_empty":           "Nenhum plano ainda.",
		"billing_plan_in_use":           "Uma assinatura ainda usa este plano.",
		"billing_invoice":               "Fatura",
		"billing_amount":                "Valor",
		"billing_issued":                "Emitida",
		"billing_paid":                  "Paga",
		"billing_open":                  "Em aberto",
		"billing_invoices_empty":        "Nenhuma fatura ainda.",
		"billing_csv":                   "Exportar CSV",
		"billing_state_trial":           "Teste",
		"billing_state_active":          "Ativa",
		"billing_state_past_due":        "Em atraso",
		"billing_state_canceled":        "Cancelada",
		"billing_mail_failed_subject":   "Seu pagamento não foi aprovado",
		"billing_mail_failed_body":      "Não conseguimos cobrar a sua assinatura. Vamos tentar de novo; depois da terceira cobrança falha a assinatura é cancelada.",
		"billing_mail_canceled_subject": "Sua assinatura foi cancelada",
		"billing_mail_canceled_body":    "Depois de três cobranças falhas a assinatura foi cancelada. Você pode assinar de novo quando quiser.",
	}
}
