package recipes

// words is the text the recipes write into the project, per language.
//
// It is a table and not a translation mechanism, which is the same trade the
// rest of the scaffold makes: what comes out is a file somebody owns and
// edits, so a third language is a find-and-replace in their own code rather
// than a feature of ours.
var words = func(lang string) map[string]string {
	if lang == "pt" {
		return map[string]string{
			"keys_usage": "Uso da API",

			"search_title": "Busca",
			"search_kind":  "Exemplos",

			"conn_title":       "Conexões",
			"conn_desc":        "Os serviços externos com que esta aplicação fala. O segredo fica selado e nunca volta para a tela.",
			"conn_api":         "APIs",
			"conn_mcp":         "Servidores MCP",
			"conn_saved":       "Conexão salva.",
			"conn_deleted":     "Conexão apagada.",
			"conn_test_ok":     "Conexão testada: respondeu.",
			"conn_test_failed": "O teste falhou:",

			"audit_title": "Auditoria",
			"audit_desc":  "Quem fez o quê, em quê, e de onde.",

			"settings_title":        "Configurações",
			"settings_saved":        "Configurações salvas.",
			"settings_name":         "Nome da aplicação",
			"settings_support":      "E-mail de suporte",
			"settings_days":         "Dias até expirar",
			"settings_default_name": "Minha aplicação",

			"keys_title":     "Chaves de API",
			"keys_desc":      "A chave aparece uma vez, quando é criada. O que fica guardado é o hash dela.",
			"keys_name":      "Nome",
			"keys_scopes":    "Escopos",
			"keys_create":    "Criar chave",
			"keys_created":   "Chave criada. Copie agora.",
			"keys_revoked":   "Chave revogada.",
			"keys_need_name": "dê um nome à chave: é por ele que alguém vai saber qual revogar",

			"login_title":    "Entrar",
			"login_email":    "E-mail",
			"login_password": "Senha",
			"login_wrong":    "E-mail ou senha inválidos.",
			"login_empty":    "Ninguém pode entrar ainda: defina ADMIN_EMAIL e ADMIN_PASSWORD e reinicie.",

			"users_title":       "Usuários",
			"users_desc":        "Quem entra, com qual papel. Convidar cria a pessoa sem senha: quem a define é ela, no link.",
			"users_email":       "E-mail",
			"users_name":        "Nome",
			"users_role":        "Papel",
			"users_state":       "Estado",
			"users_created":     "Criado",
			"users_active":      "ativo",
			"users_inactive":    "inativo",
			"users_invite":      "Convidar",
			"users_invited":     "Convite criado. O link vale 48 horas.",
			"users_invite_link": "Link do convite",
			"users_need_email":  "diga o e-mail de quem você está convidando",
			"users_save":        "Salvar",
			"users_activate":    "Ativar",
			"users_deactivate":  "Desativar",
			"users_reset":       "Resetar senha",
			"users_reset_ask":   "Resetar a senha desta pessoa?",
			"users_reset_desc":  "A senha atual para de valer e um link novo é emitido.",
			"users_reset_done":  "Link novo emitido. O anterior parou de valer.",
			"users_none":        "Ninguém aqui ainda.",

			"invite_title":    "Defina sua senha",
			"invite_password": "Senha",
			"invite_submit":   "Salvar e entrar",
			"invite_invalid":  "Este convite não vale mais.",
			"invite_short":    "A senha precisa de pelo menos 12 caracteres.",

			"perms_title":       "Permissões",
			"perms_desc":        "Um papel por linha, um módulo por coluna. Sem JavaScript.",
			"perms_none":        "sem acesso",
			"perms_save":        "Salvar",
			"perms_saved":       "Permissões salvas.",
			"perms_roles":       "Papéis",
			"perms_role":        "Papel",
			"perms_who":         "Quem tem",
			"perms_nobody":      "ninguém",
			"perms_new_role":    "Papel novo (letras minúsculas, dígitos e hífen)",
			"perms_create":      "Criar papel",
			"perms_created":     "Papel criado. Ele nasce com o que o leitor tem: ajuste a linha dele na matriz.",
			"perms_invalid":     "Um papel é letras minúsculas, dígitos e hífen, até 30.",
			"perms_exists":      "Esse papel já existe.",
			"perms_delete":      "Remover",
			"perms_delete_ask":  "Remover este papel?",
			"perms_delete_desc": "Ninguém o tem; a linha dele sai da matriz.",
			"perms_deleted":     "Papel removido.",
			"perms_in_use":      "Alguém ainda tem esse papel: troque o papel dessa pessoa antes.",
			"perms_mine":        "O que eu posso",
			"perms_mine_desc":   "A matriz vista do seu lado: o nível que você tem em cada módulo.",
			"perms_module":      "Módulo",
			"perms_level":       "Nível",

			"profile_title":           "Minha conta",
			"profile_name":            "Nome",
			"profile_save":            "Salvar",
			"profile_saved":           "Nome salvo.",
			"profile_need_name":       "Diga um nome.",
			"profile_password":        "Senha",
			"profile_password_desc":   "Trocar a senha fecha esta sessão: entre de novo com a nova.",
			"profile_current":         "Senha atual",
			"profile_new":             "Senha nova",
			"profile_change":          "Trocar senha",
			"profile_wrong":           "A senha atual não confere, ou a nova tem menos de 12 caracteres.",
			"profile_password_done":   "Senha trocada. Entre de novo.",
			"profile_gone":            "Sua sessão acabou.",
			"profile_email":           "E-mail",
			"profile_email_desc":      "Um link vai para o endereço novo; o e-mail só muda quando ele é aberto.",
			"profile_new_email":       "E-mail novo",
			"profile_email_change":    "Mandar confirmação",
			"profile_email_sent":      "Confirmação enviada para o endereço novo. Abra o link de lá.",
			"profile_email_nomail":    "Ninguém manda e-mail neste app ainda: sem confirmação no endereço novo, o e-mail não muda. `trilha add mail` liga isso.",
			"profile_email_invalid":   "Isso não é um e-mail, é o atual, ou é de outra conta.",
			"profile_email_not_yours": "Este link é de outra conta.",
			"profile_email_done":      "E-mail trocado.",
			"profile_sessions":        "Sessões",
			"profile_sessions_desc":   "Onde mais esta conta está aberta.",
			"profile_since":           "Desde",
			"profile_seen":            "Última vez",
			"profile_this":            "esta",
			"profile_end_others":      "Encerrar as outras",
			"profile_ended_others":    "As outras sessões foram encerradas.",
			"profile_no_list":         "O guarda de sessões deste app não lista sessões por dono.",

			"hooks_title": "Webhooks",
			"hooks_desc":  "O que este app avisa para fora. A entrega sai fora da requisição, assinada, e tenta de novo quando o outro lado está fora do ar.",

			"tasks_title": "Tarefas",
			"tasks_desc":  "O trabalho longo roda fora da requisição; esta tela lê o estado que ele deixou.",
			"tasks_key":   "Chave (o que está sendo processado)",
			"tasks_run":   "Rodar",

			"tenant_title":           "Organizações",
			"tenant_desc":            "Escolha em qual você está. Trocar muda o que você vê, e fica registrado.",
			"tenant_current":         "atual",
			"tenant_none":            "Você ainda não pertence a nenhuma organização.",
			"tenant_switched":        "Organização trocada.",
			"tenant_denied":          "Você não pertence a essa organização.",
			"tenant_gone":            "Sua sessão acabou.",
			"tenant_name":            "Nome",
			"tenant_members":         "Membros",
			"tenant_switch":          "Trocar para",
			"tenant_inactive":        "inativa",
			"tenant_create":          "Nova organização",
			"tenant_created":         "Organização criada. Você é membro dela.",
			"tenant_name_empty":      "Dê um nome.",
			"tenant_exists":          "Já existe uma organização com esse nome.",
			"tenant_activate":        "Ativar",
			"tenant_deactivate":      "Desativar",
			"tenant_deactivate_ask":  "Desativar esta organização?",
			"tenant_deactivate_desc": "Nada é apagado. Ninguém troca para ela até ser ativada de novo.",
			"tenant_toggled":         "Organização atualizada.",
			"tenant_config":          "Configuração da organização em que você está",
			"tenant_save":            "Salvar",
			"tenant_cfg_tz":          "Fuso horário",
			"tenant_cfg_limit":       "Linhas por página",

			"mail_brand":           "Minha aplicação",
			"mail_welcome_subject": "Bem-vindo ao",
			"mail_welcome_hi":      "Olá, %s! Sua conta está pronta.",
			"mail_welcome_button":  "Entrar",
			"mail_welcome_hint":    "Se o botão não funcionar, cole este endereço no navegador:",
			"mail_confirm_subject": "Confirme seu e-mail novo no",
			"mail_confirm_hi":      "Alguém pediu para usar este endereço na conta. Se foi você, confirme:",
			"mail_confirm_button":  "Confirmar e-mail",
		}
	}
	return map[string]string{
		"keys_usage": "API usage",

		"search_title": "Search",
		"search_kind":  "Examples",

		"conn_title":       "Connections",
		"conn_desc":        "The external services this application talks to. The secret is sealed and never comes back to the screen.",
		"conn_api":         "APIs",
		"conn_mcp":         "MCP servers",
		"conn_saved":       "Connection saved.",
		"conn_deleted":     "Connection deleted.",
		"conn_test_ok":     "Connection tested: it answered.",
		"conn_test_failed": "The test failed:",

		"audit_title": "Audit trail",
		"audit_desc":  "Who did what, to what, and from where.",

		"settings_title":        "Settings",
		"settings_saved":        "Settings saved.",
		"settings_name":         "Application name",
		"settings_support":      "Support e-mail",
		"settings_days":         "Days before expiry",
		"settings_default_name": "My application",

		"keys_title":     "API keys",
		"keys_desc":      "A key is shown once, when it is created. What is stored is its hash.",
		"keys_name":      "Name",
		"keys_scopes":    "Scopes",
		"keys_create":    "Create key",
		"keys_created":   "Key created. Copy it now.",
		"keys_revoked":   "Key revoked.",
		"keys_need_name": "give the key a name: it is how somebody later knows which one to revoke",

		"login_title":    "Sign in",
		"login_email":    "E-mail",
		"login_password": "Password",
		"login_wrong":    "Wrong e-mail or password.",
		"login_empty":    "Nobody can sign in yet: set ADMIN_EMAIL and ADMIN_PASSWORD and restart.",

		"users_title":       "Users",
		"users_desc":        "Who gets in, with what role. Inviting creates the person with no password: they set it, from the link.",
		"users_email":       "E-mail",
		"users_name":        "Name",
		"users_role":        "Role",
		"users_state":       "State",
		"users_created":     "Created",
		"users_active":      "active",
		"users_inactive":    "inactive",
		"users_invite":      "Invite",
		"users_invited":     "Invitation created. The link is worth 48 hours.",
		"users_invite_link": "Invitation link",
		"users_need_email":  "say the e-mail of whoever you are inviting",
		"users_save":        "Save",
		"users_activate":    "Activate",
		"users_deactivate":  "Deactivate",
		"users_reset":       "Reset password",
		"users_reset_ask":   "Reset this person's password?",
		"users_reset_desc":  "The current password stops working and a new link is issued.",
		"users_reset_done":  "New link issued. The previous one stopped working.",
		"users_none":        "Nobody here yet.",

		"invite_title":    "Set your password",
		"invite_password": "Password",
		"invite_submit":   "Save and sign in",
		"invite_invalid":  "This invitation is no longer valid.",
		"invite_short":    "The password needs at least 12 characters.",

		"perms_title":       "Permissions",
		"perms_desc":        "A role per row, a module per column. No JavaScript.",
		"perms_none":        "no access",
		"perms_save":        "Save",
		"perms_saved":       "Permissions saved.",
		"perms_roles":       "Roles",
		"perms_role":        "Role",
		"perms_who":         "Who has it",
		"perms_nobody":      "nobody",
		"perms_new_role":    "New role (lower-case letters, digits and dashes)",
		"perms_create":      "Create role",
		"perms_created":     "Role created. It starts with what leitor has: adjust its row in the matrix.",
		"perms_invalid":     "A role is lower-case letters, digits and dashes, up to 30.",
		"perms_exists":      "That role already exists.",
		"perms_delete":      "Remove",
		"perms_delete_ask":  "Remove this role?",
		"perms_delete_desc": "Nobody has it; its row leaves the matrix.",
		"perms_deleted":     "Role removed.",
		"perms_in_use":      "Somebody still has that role: change their role first.",
		"perms_mine":        "What I can do",
		"perms_mine_desc":   "The matrix from your side: the level you have on each module.",
		"perms_module":      "Module",
		"perms_level":       "Level",

		"profile_title":           "My account",
		"profile_name":            "Name",
		"profile_save":            "Save",
		"profile_saved":           "Name saved.",
		"profile_need_name":       "Say a name.",
		"profile_password":        "Password",
		"profile_password_desc":   "Changing the password ends this session: sign in again with the new one.",
		"profile_current":         "Current password",
		"profile_new":             "New password",
		"profile_change":          "Change password",
		"profile_wrong":           "The current password does not match, or the new one is shorter than 12 characters.",
		"profile_password_done":   "Password changed. Sign in again.",
		"profile_gone":            "Your session ended.",
		"profile_email":           "E-mail",
		"profile_email_desc":      "A link goes to the new address; the e-mail only changes when it is opened.",
		"profile_new_email":       "New e-mail",
		"profile_email_change":    "Send confirmation",
		"profile_email_sent":      "Confirmation sent to the new address. Open the link from there.",
		"profile_email_nomail":    "Nobody sends e-mail in this app yet: without a confirmation at the new address, the e-mail does not change. `trilha add mail` wires it.",
		"profile_email_invalid":   "That is not an e-mail, it is the current one, or it belongs to another account.",
		"profile_email_not_yours": "This link belongs to another account.",
		"profile_email_done":      "E-mail changed.",
		"profile_sessions":        "Sessions",
		"profile_sessions_desc":   "Where else this account is signed in.",
		"profile_since":           "Since",
		"profile_seen":            "Last seen",
		"profile_this":            "this one",
		"profile_end_others":      "End the others",
		"profile_ended_others":    "The other sessions were ended.",
		"profile_no_list":         "This app's session store does not list sessions by owner.",

		"hooks_title": "Webhooks",
		"hooks_desc":  "What this application announces to the outside. The delivery leaves outside the request, signed, and tries again when the other side is down.",

		"tasks_title": "Tasks",
		"tasks_desc":  "The long work runs outside the request; this screen reads the state it left behind.",
		"tasks_key":   "Key (what is being worked on)",
		"tasks_run":   "Run",

		"mail_brand":           "My application",
		"mail_welcome_subject": "Welcome to",
		"mail_welcome_hi":      "Hello, %s! Your account is ready.",
		"mail_welcome_button":  "Sign in",
		"mail_welcome_hint":    "If the button does not work, paste this address into your browser:",
		"mail_confirm_subject": "Confirm your new e-mail at",
		"mail_confirm_hi":      "Somebody asked to use this address on the account. If it was you, confirm:",
		"mail_confirm_button":  "Confirm e-mail",

		"blob_title": "Files",
		"blob_desc":  "What people send is stored by the digest of the content: the same file twice takes space once.",
		"blob_field": "Files",
		"blob_send":  "Send",
		"blob_empty": "Nothing stored yet.",
		"blob_name":  "Name",
		"blob_type":  "Type",
		"blob_size":  "Size",
		"blob_when":  "When",

		"share_title": "Shared with you",
		"share_desc":  "This link is worth something for a while and then stops. Nobody needed an account to open it.",
		"share_item":  "Item %s.",

		"tenant_title":           "Organisations",
		"tenant_desc":            "Pick which one you are in. Switching changes what you see, and is recorded.",
		"tenant_current":         "current",
		"tenant_none":            "You do not belong to any organisation yet.",
		"tenant_switched":        "Organisation switched.",
		"tenant_denied":          "You do not belong to that organisation.",
		"tenant_gone":            "Your session ended.",
		"tenant_name":            "Name",
		"tenant_members":         "Members",
		"tenant_switch":          "Switch to",
		"tenant_inactive":        "inactive",
		"tenant_create":          "New organisation",
		"tenant_created":         "Organisation created. You are a member of it.",
		"tenant_name_empty":      "Give it a name.",
		"tenant_exists":          "An organisation with that name already exists.",
		"tenant_activate":        "Activate",
		"tenant_deactivate":      "Deactivate",
		"tenant_deactivate_ask":  "Deactivate this organisation?",
		"tenant_deactivate_desc": "Nothing is deleted. Nobody can switch into it until it is activated again.",
		"tenant_toggled":         "Organisation updated.",
		"tenant_config":          "Settings of the organisation you are in",
		"tenant_save":            "Save",
		"tenant_cfg_tz":          "Time zone",
		"tenant_cfg_limit":       "Rows per page",

		"inbox_title":     "Approvals",
		"inbox_desc":      "What is waiting for a decision of yours. The deadline expires on its own; the decision is recorded with your name on it.",
		"inbox_recent":    "Latest decisions",
		"inbox_done":      "Decision recorded.",
		"inbox_not_yours": "This request is not yours to decide.",
	}
}
