package recipes

// platformWordsEN is the text of the platform recipes (spec 162): billing,
// notify and admin. A table of its own so the three recipes read as one
// block, merged into words by language like the rest.
func platformWordsEN() map[string]string {
	return map[string]string{
		"billing_title":                 "Billing",
		"billing_desc":                  "Subscriptions by state. The provider charges the card; this application decides what each event means.",
		"billing_plans":                 "Plans",
		"billing_invoices":              "Invoices",
		"billing_customer":              "Customer",
		"billing_plan":                  "Plan",
		"billing_subscription":          "Subscription",
		"billing_state":                 "State",
		"billing_attempts":              "Failed charges",
		"billing_all":                   "All states",
		"billing_empty":                 "No subscriptions yet.",
		"billing_search":                "Search by e-mail",
		"billing_plan_name":             "Name",
		"billing_plan_cents":            "Price (cents)",
		"billing_plan_currency":         "Currency",
		"billing_plan_interval":         "Interval",
		"billing_plan_month":            "Monthly",
		"billing_plan_year":             "Yearly",
		"billing_plan_save":             "Create plan",
		"billing_plan_delete":           "Delete",
		"billing_plans_empty":           "No plans yet.",
		"billing_plan_in_use":           "A subscription still uses this plan.",
		"billing_invoice":               "Invoice",
		"billing_amount":                "Amount",
		"billing_issued":                "Issued",
		"billing_paid":                  "Paid",
		"billing_open":                  "Open",
		"billing_invoices_empty":        "No invoices yet.",
		"billing_csv":                   "Export CSV",
		"billing_state_trial":           "Trial",
		"billing_state_active":          "Active",
		"billing_state_past_due":        "Past due",
		"billing_state_canceled":        "Canceled",
		"billing_mail_failed_subject":   "Your payment did not go through",
		"billing_mail_failed_body":      "We could not charge your subscription. We will try again; after the third failed charge the subscription is canceled.",
		"billing_mail_canceled_subject": "Your subscription was canceled",
		"billing_mail_canceled_body":    "After three failed charges the subscription was canceled. You can subscribe again whenever you want.",
		"notify_title":                  "Notifications",
		"notify_desc":                   "How you want to be told things. Quiet hours hold messages until they end; the digest sends one e-mail a day instead of one per notification.",
		"notify_channel":                "Channel",
		"notify_channel_mail":           "E-mail",
		"notify_channel_webhook":        "Webhook",
		"notify_channel_whatsapp":       "WhatsApp",
		"notify_digest":                 "Daily digest",
		"notify_quiet_from":             "Quiet from (hour)",
		"notify_quiet_to":               "Quiet until (hour)",
		"notify_phone":                  "Phone (for WhatsApp)",
		"notify_save":                   "Save",
		"notify_saved":                  "Preferences saved.",
		"notify_unwired":                "This channel is not available in this application.",
		"notify_recent":                 "Sent to you",
		"notify_empty":                  "Nothing sent to you yet.",
		"notify_subject":                "Subject",
		"notify_state":                  "State",
		"notify_to":                     "To",
		"notify_error":                  "Error",
		"notify_outbox":                 "Outbox",
		"notify_outbox_desc":            "Everything this application decided to tell somebody, and what happened to it. What was held back can be resent.",
		"notify_outbox_empty":           "Nothing in the outbox yet.",
		"notify_resend":                 "Resend",
		"notify_still_limited":          "The channel is still at its limit for this person.",
		"notify_digest_now":             "Send today's digest",
		"notify_digest_subject":         "Your notifications",
		"notify_digest_intro":           "What arrived since the last digest:",
		"notify_settings":               "Limits",
		"notify_settings_invalid":       "The limits were not saved: check the values.",
		"notify_limit":                  "Messages per channel, per person, per hour",
		"notify_digest_hour":            "Hour of the daily digest",
		"notify_state_sent":             "Sent",
		"notify_state_held":             "Held (quiet hours)",
		"notify_state_digest":           "In the digest",
		"notify_state_limited":          "Limited",
		"notify_state_failed":           "Failed",
		"admin_title":                   "Administration",
		"admin_desc":                    "Only the admin role gets here. Every screen under /admin — the one you write tomorrow included — is closed to everybody else.",
		"admin_open":                    "Open",
		"admin_users":                   "Users and roles",
		"admin_users_desc":              "Invite, change a role, deactivate. Every decision goes to the trail.",
		"admin_audit":                   "Audit trail",
		"admin_audit_desc":              "Who did what, to what, from where.",
		"admin_approvals":               "Approvals",
		"admin_approvals_desc":          "What is waiting for a decision.",
		"admin_pending":                 "Pending",
		"admin_search":                  "Search",
		"admin_search_desc":             "Everything the application indexed.",
	}
}

// platformWordsPT is the Portuguese table of the platform recipes.
func platformWordsPT() map[string]string {
	return map[string]string{
		"billing_title":                 "Cobrança",
		"billing_desc":                  "Assinaturas por estado. O provedor cobra o cartão; este app decide o que cada evento significa.",
		"billing_plans":                 "Planos",
		"billing_invoices":              "Faturas",
		"billing_customer":              "Cliente",
		"billing_plan":                  "Plano",
		"billing_subscription":          "Assinatura",
		"billing_state":                 "Estado",
		"billing_attempts":              "Cobranças falhas",
		"billing_all":                   "Todos os estados",
		"billing_empty":                 "Nenhuma assinatura ainda.",
		"billing_search":                "Buscar por e-mail",
		"billing_plan_name":             "Nome",
		"billing_plan_cents":            "Preço (centavos)",
		"billing_plan_currency":         "Moeda",
		"billing_plan_interval":         "Intervalo",
		"billing_plan_month":            "Mensal",
		"billing_plan_year":             "Anual",
		"billing_plan_save":             "Criar plano",
		"billing_plan_delete":           "Apagar",
		"billing_plans_empty":           "Nenhum plano ainda.",
		"billing_plan_in_use":           "Uma assinatura ainda usa este plano.",
		"billing_invoice":               "Fatura",
		"billing_amount":                "Valor",
		"billing_issued":                "Emitida",
		"billing_paid":                  "Paga",
		"billing_open":                  "Em aberto",
		"billing_invoices_empty":        "Nenhuma fatura ainda.",
		"billing_csv":                   "Exportar CSV",
		"billing_state_trial":           "Teste",
		"billing_state_active":          "Ativa",
		"billing_state_past_due":        "Em atraso",
		"billing_state_canceled":        "Cancelada",
		"billing_mail_failed_subject":   "Seu pagamento não foi aprovado",
		"billing_mail_failed_body":      "Não conseguimos cobrar a sua assinatura. Vamos tentar de novo; depois da terceira cobrança falha a assinatura é cancelada.",
		"billing_mail_canceled_subject": "Sua assinatura foi cancelada",
		"billing_mail_canceled_body":    "Depois de três cobranças falhas a assinatura foi cancelada. Você pode assinar de novo quando quiser.",
		"notify_title":                  "Notificações",
		"notify_desc":                   "Como você quer ser avisado. O horário silencioso segura as mensagens até acabar; o digesto manda um e-mail por dia em vez de um por notificação.",
		"notify_channel":                "Canal",
		"notify_channel_mail":           "E-mail",
		"notify_channel_webhook":        "Webhook",
		"notify_channel_whatsapp":       "WhatsApp",
		"notify_digest":                 "Digesto diário",
		"notify_quiet_from":             "Silêncio a partir de (hora)",
		"notify_quiet_to":               "Silêncio até (hora)",
		"notify_phone":                  "Telefone (para o WhatsApp)",
		"notify_save":                   "Salvar",
		"notify_saved":                  "Preferências salvas.",
		"notify_unwired":                "Este canal não está disponível neste app.",
		"notify_recent":                 "Enviadas para você",
		"notify_empty":                  "Nada enviado para você ainda.",
		"notify_subject":                "Assunto",
		"notify_state":                  "Estado",
		"notify_to":                     "Para",
		"notify_error":                  "Erro",
		"notify_outbox":                 "Fila de saída",
		"notify_outbox_desc":            "Tudo o que este app decidiu avisar a alguém, e o que aconteceu com cada aviso. O que ficou retido pode ser reenviado.",
		"notify_outbox_empty":           "Nada na fila ainda.",
		"notify_resend":                 "Reenviar",
		"notify_still_limited":          "O canal continua no limite para esta pessoa.",
		"notify_digest_now":             "Enviar o digesto de hoje",
		"notify_digest_subject":         "Suas notificações",
		"notify_digest_intro":           "O que chegou desde o último digesto:",
		"notify_settings":               "Limites",
		"notify_settings_invalid":       "Os limites não foram salvos: confira os valores.",
		"notify_limit":                  "Mensagens por canal, por pessoa, por hora",
		"notify_digest_hour":            "Hora do digesto diário",
		"notify_state_sent":             "Enviada",
		"notify_state_held":             "Retida (silêncio)",
		"notify_state_digest":           "No digesto",
		"notify_state_limited":          "Limitada",
		"notify_state_failed":           "Falhou",
		"admin_title":                   "Administração",
		"admin_desc":                    "Só o papel admin chega aqui. Toda tela sob /admin — inclusive a que você escrever amanhã — fica fechada para os outros.",
		"admin_open":                    "Abrir",
		"admin_users":                   "Usuários e papéis",
		"admin_users_desc":              "Convidar, trocar papel, desativar. Toda decisão vai para a trilha.",
		"admin_audit":                   "Trilha de auditoria",
		"admin_audit_desc":              "Quem fez o quê, em quê, de onde.",
		"admin_approvals":               "Aprovações",
		"admin_approvals_desc":          "O que espera uma decisão.",
		"admin_pending":                 "Pendentes",
		"admin_search":                  "Busca",
		"admin_search_desc":             "Tudo o que o app indexou.",
	}
}
