// Code generated by trilha. DO NOT EDIT.

package main

import (
	"embed"

	trilha "github.com/emersonjoe/trilha"
	app "github.com/emersonjoe/trilha/examples/sso/app"
	app_api "github.com/emersonjoe/trilha/examples/sso/app/api"
	app_api_eu "github.com/emersonjoe/trilha/examples/sso/app/api/eu"
	app_entrar "github.com/emersonjoe/trilha/examples/sso/app/entrar"
	app_entrar_retorno "github.com/emersonjoe/trilha/examples/sso/app/entrar/retorno"
	app_painel "github.com/emersonjoe/trilha/examples/sso/app/painel"
	app_painel_relatorio "github.com/emersonjoe/trilha/examples/sso/app/painel/relatorio"
	app_sair "github.com/emersonjoe/trilha/examples/sso/app/sair"
)

//go:embed public
var publicFS embed.FS

// newApp builds the application. Tests can call it and use a.Handler().
func newApp() *trilha.App {
	cfg := trilha.ConfigFromEnv()
	cfg.Public = trilha.PublicFS(publicFS, "public")
	a := trilha.New(cfg)
	if err := app.Setup(a); err != nil {
		trilha.Fatal(err)
	}
	a.SetRootLayout(app.Layout)
	a.Register(trilha.Route{
		Pattern: "/",
		Page:    app.Page,
		Layouts: []trilha.LayoutFunc{app.Layout},
	})
	a.Register(trilha.Route{
		Pattern: "/api/eu",
		Methods: map[string]trilha.HandlerFunc{
			"GET": app_api_eu.GET,
		},
		Middlewares: []trilha.MiddlewareFunc{app_api.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/entrar",
		Kind:    app_entrar.Kind,
		Methods: map[string]trilha.HandlerFunc{
			"GET": app_entrar.GET,
		},
	})
	a.Register(trilha.Route{
		Pattern: "/entrar/retorno",
		Kind:    app_entrar_retorno.Kind,
		Methods: map[string]trilha.HandlerFunc{
			"GET": app_entrar_retorno.GET,
		},
	})
	a.Register(trilha.Route{
		Pattern:     "/painel",
		Page:        app_painel.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app_painel.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/painel/relatorio",
		Page:        app_painel_relatorio.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app_painel.Middleware, app_painel_relatorio.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/sair",
		Kind:    app_sair.Kind,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_sair.POST,
		},
	})
	return a
}

func main() {
	trilha.Run(newApp())
}
