// Package uidoc is the catalogue of the ui kit: for every exported symbol, the
// signature, what it is for and how it is called. The source is the doc
// comment in ui/ — nothing here is written by hand — and the result is
// catalog.json, generated by the test with -update and committed, because
// go:embed does not reach outside the package and the CLI cannot count on the
// source being nearby.
package uidoc

import (
	_ "embed"
	"encoding/json"
	"sort"
	"strings"
	"sync"
)

//go:embed catalog.json
var catalogJSON []byte

// Field is one field of an options struct.
type Field struct {
	Name string `json:"name"`
	Type string `json:"type"`
	Doc  string `json:"doc,omitempty"`
}

// Component is one exported symbol of the ui package.
type Component struct {
	Name string `json:"name"`
	// Kind is "func" or "type".
	Kind string `json:"kind"`
	// Group is the section it belongs to — the banner in the source, or the
	// file it lives in.
	Group     string `json:"group"`
	Signature string `json:"signature"`
	// Doc is the comment without the example block; Summary is its first
	// sentence.
	Doc     string `json:"doc"`
	Summary string `json:"summary"`
	// Example is the indented block of the doc comment, dedented.
	Example string `json:"example,omitempty"`
	// Fields are the exported fields of a struct type.
	Fields []Field `json:"fields,omitempty"`
	// See are the other symbols the doc mentions.
	See []string `json:"see,omitempty"`
}

var (
	once   sync.Once
	parsed []Component
)

// Components returns the catalogue in source order.
func Components() []Component {
	once.Do(func() {
		if err := json.Unmarshal(catalogJSON, &parsed); err != nil {
			panic("uidoc: bad catalog: " + err.Error())
		}
	})
	return parsed
}

// JSON returns the catalogue as it is stored.
func JSON() []byte { return catalogJSON }

// Lookup finds one component by name, with or without the ui. prefix and
// ignoring case — what somebody types is rarely what the file says.
func Lookup(name string) (Component, bool) {
	want := strings.ToLower(strings.TrimPrefix(strings.TrimSpace(name), "ui."))
	for _, c := range Components() {
		if strings.ToLower(c.Name) == want {
			return c, true
		}
	}
	return Component{}, false
}

// Similar returns the names closest to an unknown one, so a typo answers with
// the list of what it almost was instead of nothing.
func Similar(name string) []string {
	want := strings.ToLower(strings.TrimPrefix(strings.TrimSpace(name), "ui."))
	if want == "" {
		return nil
	}
	type scored struct {
		name string
		d    int
	}
	var out []scored
	for _, c := range Components() {
		low := strings.ToLower(c.Name)
		switch {
		case strings.Contains(low, want) || strings.Contains(want, low):
			out = append(out, scored{c.Name, 0})
		case distance(low, want) <= 2:
			out = append(out, scored{c.Name, distance(low, want)})
		}
	}
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].d != out[j].d {
			return out[i].d < out[j].d
		}
		return out[i].name < out[j].name
	})
	names := make([]string, 0, len(out))
	for i, s := range out {
		if i == 5 {
			break
		}
		names = append(names, s.name)
	}
	return names
}

// distance is the Levenshtein distance, one row at a time.
func distance(a, b string) int {
	prev := make([]int, len(b)+1)
	cur := make([]int, len(b)+1)
	for j := range prev {
		prev[j] = j
	}
	for i := 1; i <= len(a); i++ {
		cur[0] = i
		for j := 1; j <= len(b); j++ {
			cost := 1
			if a[i-1] == b[j-1] {
				cost = 0
			}
			cur[j] = min(min(cur[j-1]+1, prev[j]+1), prev[j-1]+cost)
		}
		prev, cur = cur, prev
	}
	return prev[len(b)]
}
