// Code generated by trilha. DO NOT EDIT.

package main

import (
	"embed"

	trilha "github.com/emersonjoe/trilha"
	app "github.com/emersonjoe/trilha/site/app"
	app_aprender "github.com/emersonjoe/trilha/site/app/aprender"
	app_aprender_slug_ "github.com/emersonjoe/trilha/site/app/aprender/slug_"
	app_referencia "github.com/emersonjoe/trilha/site/app/referencia"
	app_referencia_slug_ "github.com/emersonjoe/trilha/site/app/referencia/slug_"
)

//go:embed public
var publicFS embed.FS

// newApp builds the application. Tests can call it and use a.Handler().
func newApp() *trilha.App {
	cfg := trilha.ConfigFromEnv()
	cfg.Public = trilha.PublicFS(publicFS, "public")
	a := trilha.New(cfg)
	if err := app.Setup(a); err != nil {
		trilha.Fatal(err)
	}
	a.SetRootLayout(app.Layout)
	a.SetNotFound(app.NotFound)
	a.Register(trilha.Route{
		Pattern:     "/",
		Page:        app.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/aprender",
		Page:        app_aprender.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/aprender/{slug}",
		Page:        app_aprender_slug_.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/referencia",
		Page:        app_referencia.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/referencia/{slug}",
		Page:        app_referencia_slug_.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	return a
}

func main() {
	trilha.Run(newApp())
}
