// Code generated by trilha. DO NOT EDIT.

//go:generate trilha gen

package main

import (
	"embed"

	trilha "github.com/emersonjoe/trilha"
	app "github.com/emersonjoe/trilha/examples/blog/app"
	app_admin "github.com/emersonjoe/trilha/examples/blog/app/admin"
	app_api "github.com/emersonjoe/trilha/examples/blog/app/api"
	app_api_posts "github.com/emersonjoe/trilha/examples/blog/app/api/posts"
	app_api_posts_id_ "github.com/emersonjoe/trilha/examples/blog/app/api/posts/id_"
	app_blog "github.com/emersonjoe/trilha/examples/blog/app/blog"
	app_blog_novo "github.com/emersonjoe/trilha/examples/blog/app/blog/novo"
	app_blog_slug_ "github.com/emersonjoe/trilha/examples/blog/app/blog/slug_"
	app_docs_path__ "github.com/emersonjoe/trilha/examples/blog/app/docs/path__"
	app_login "github.com/emersonjoe/trilha/examples/blog/app/login"
	app_marketing_ "github.com/emersonjoe/trilha/examples/blog/app/marketing-"
	app_marketing__precos "github.com/emersonjoe/trilha/examples/blog/app/marketing-/precos"
	app_marketing__sobre "github.com/emersonjoe/trilha/examples/blog/app/marketing-/sobre"
	app_painel_ "github.com/emersonjoe/trilha/examples/blog/app/painel-"
	app_painel__painel "github.com/emersonjoe/trilha/examples/blog/app/painel-/painel"
	app_painel__relatorio "github.com/emersonjoe/trilha/examples/blog/app/painel-/relatorio"
)

//go:embed public
var publicFS embed.FS

// newApp builds the application. Tests can call it and use a.Handler().
func newApp() *trilha.App {
	cfg := trilha.ConfigFromEnv()
	cfg.Public = trilha.PublicFS(publicFS, "public")
	if err := app.Config(&cfg); err != nil {
		trilha.Fatal(err)
	}
	a := trilha.New(cfg)
	if err := app.Setup(a); err != nil {
		trilha.Fatal(err)
	}
	a.SetRootLayout(app.Layout)
	a.SetNotFound(app.NotFound)
	a.SetErrorPage(app.Error)
	a.Register(trilha.Route{
		Pattern:     "/",
		Page:        app.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/admin",
		Page:        app_admin.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware, app_admin.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/api/posts",
		Methods: map[string]trilha.HandlerFunc{
			"GET":  app_api_posts.GET,
			"POST": app_api_posts.POST,
		},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware, app_api.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/api/posts/{id}",
		Methods: map[string]trilha.HandlerFunc{
			"DELETE": app_api_posts_id_.DELETE,
			"GET":    app_api_posts_id_.GET,
		},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware, app_api.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/blog",
		Page:        app_blog.Page,
		Layouts:     []trilha.LayoutFunc{app_blog.Layout, app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/blog/novo",
		Page:    app_blog_novo.Page,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_blog_novo.POST,
		},
		Layouts:     []trilha.LayoutFunc{app_blog.Layout, app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/blog/{slug}",
		Page:    app_blog_slug_.Page,
		Methods: map[string]trilha.HandlerFunc{
			"DELETE": app_blog_slug_.DELETE,
			"POST":   app_blog_slug_.POST,
		},
		Layouts:     []trilha.LayoutFunc{app_blog.Layout, app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/docs/{path...}",
		Page:        app_docs_path__.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/login",
		Page:    app_login.Page,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_login.POST,
		},
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/painel",
		Page:        app_painel__painel.Page,
		Layouts:     []trilha.LayoutFunc{app_painel_.Layout, app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware, app_painel_.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/precos",
		Page:        app_marketing__precos.Page,
		Layouts:     []trilha.LayoutFunc{app_marketing_.Layout, app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/relatorio",
		Page:        app_painel__relatorio.Page,
		Layouts:     []trilha.LayoutFunc{app_painel_.Layout, app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware, app_painel_.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/sobre",
		Page:        app_marketing__sobre.Page,
		Layouts:     []trilha.LayoutFunc{app_marketing_.Layout, app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	return a
}

func main() {
	trilha.Run(newApp())
}
