// Code generated by trilha. DO NOT EDIT.

//go:generate trilha gen

package main

import (
	"embed"

	trilha "github.com/emersonjoe/trilha"
	app "github.com/emersonjoe/trilha/examples/blog/app"
	app__well_known_security_txt "github.com/emersonjoe/trilha/examples/blog/app/.well-known/security.txt"
	app_admin "github.com/emersonjoe/trilha/examples/blog/app/admin"
	app_anexos "github.com/emersonjoe/trilha/examples/blog/app/anexos"
	app_anexos_nome_ "github.com/emersonjoe/trilha/examples/blog/app/anexos/nome_"
	app_anexos_nome__ver "github.com/emersonjoe/trilha/examples/blog/app/anexos/nome_/ver"
	app_api "github.com/emersonjoe/trilha/examples/blog/app/api"
	app_api_posts "github.com/emersonjoe/trilha/examples/blog/app/api/posts"
	app_api_posts_id_ "github.com/emersonjoe/trilha/examples/blog/app/api/posts/id_"
	app_blog "github.com/emersonjoe/trilha/examples/blog/app/blog"
	app_blog_novo "github.com/emersonjoe/trilha/examples/blog/app/blog/novo"
	app_blog_novo_rascunho "github.com/emersonjoe/trilha/examples/blog/app/blog/novo/rascunho"
	app_blog_ordem "github.com/emersonjoe/trilha/examples/blog/app/blog/ordem"
	app_blog_slug_ "github.com/emersonjoe/trilha/examples/blog/app/blog/slug_"
	app_docs_path__ "github.com/emersonjoe/trilha/examples/blog/app/docs/path__"
	app_documentos "github.com/emersonjoe/trilha/examples/blog/app/documentos"
	app_documentos_planilha "github.com/emersonjoe/trilha/examples/blog/app/documentos/planilha"
	app_documentos_resumo "github.com/emersonjoe/trilha/examples/blog/app/documentos/resumo"
	app_legado_ "github.com/emersonjoe/trilha/examples/blog/app/legado-"
	app_legado__legado "github.com/emersonjoe/trilha/examples/blog/app/legado-/legado"
	app_legado__legado_apagar "github.com/emersonjoe/trilha/examples/blog/app/legado-/legado/apagar"
	app_login "github.com/emersonjoe/trilha/examples/blog/app/login"
	app_marketing_ "github.com/emersonjoe/trilha/examples/blog/app/marketing-"
	app_marketing__precos "github.com/emersonjoe/trilha/examples/blog/app/marketing-/precos"
	app_marketing__sobre "github.com/emersonjoe/trilha/examples/blog/app/marketing-/sobre"
	app_mcp "github.com/emersonjoe/trilha/examples/blog/app/mcp"
	app_painel_ "github.com/emersonjoe/trilha/examples/blog/app/painel-"
	app_painel__assistente "github.com/emersonjoe/trilha/examples/blog/app/painel-/assistente"
	app_painel__painel "github.com/emersonjoe/trilha/examples/blog/app/painel-/painel"
	app_painel__relatorio "github.com/emersonjoe/trilha/examples/blog/app/painel-/relatorio"
	app_tarefas "github.com/emersonjoe/trilha/examples/blog/app/tarefas"
	app_tarefas_id_ "github.com/emersonjoe/trilha/examples/blog/app/tarefas/id_"
	app_tarefas_tentar "github.com/emersonjoe/trilha/examples/blog/app/tarefas/tentar"
	app_webhooks "github.com/emersonjoe/trilha/examples/blog/app/webhooks"
)

//go:embed public
var publicFS embed.FS

// newApp builds the application. Tests can call it and use a.Handler().
func newApp() *trilha.App {
	cfg := trilha.ConfigFromEnv()
	cfg.Public = trilha.PublicFS(publicFS, "public")
	if err := app.Config(&cfg); err != nil {
		trilha.Fatal(err)
	}
	a := trilha.New(cfg)
	if err := app.Setup(a); err != nil {
		trilha.Fatal(err)
	}
	a.SetRootLayout(app.Layout)
	a.SetNotFound(app.NotFound)
	a.SetErrorPage(app.Error)
	a.Register(trilha.Route{
		Pattern:     "/",
		Page:        app.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/.well-known/security.txt",
		CORS:    &app__well_known_security_txt.CORS,
		Methods: map[string]trilha.HandlerFunc{
			"GET": app__well_known_security_txt.GET,
		},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/admin",
		Page:        app_admin.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware, app_admin.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/anexos",
		Page:    app_anexos.Page,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_anexos.POST,
		},
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware, app_anexos.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/anexos/{nome}",
		Methods: map[string]trilha.HandlerFunc{
			"GET": app_anexos_nome_.GET,
		},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware, app_anexos.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/anexos/{nome}/ver",
		Page:        app_anexos_nome__ver.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware, app_anexos.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/api/posts",
		Kind:    app_api.Kind,
		Methods: map[string]trilha.HandlerFunc{
			"GET":  app_api_posts.GET,
			"POST": app_api_posts.POST,
		},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware, app_api.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/api/posts/{id}",
		Kind:    app_api.Kind,
		Methods: map[string]trilha.HandlerFunc{
			"DELETE": app_api_posts_id_.DELETE,
			"GET":    app_api_posts_id_.GET,
		},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware, app_api.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/assistente",
		Page:    app_painel__assistente.Page,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_painel__assistente.POST,
		},
		Layouts:     []trilha.LayoutFunc{app_painel_.Layout, app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware, app_painel_.Middleware},
		MiddlewaresByMethod: map[string][]trilha.MiddlewareFunc{
			"POST": {app_painel_.MiddlewarePOST},
		},
	})
	a.Register(trilha.Route{
		Pattern:     "/blog",
		Page:        app_blog.Page,
		Layouts:     []trilha.LayoutFunc{app_blog.Layout, app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/blog/novo",
		Page:    app_blog_novo.Page,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_blog_novo.POST,
		},
		Layouts:     []trilha.LayoutFunc{app_blog.Layout, app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/blog/novo/rascunho",
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_blog_novo_rascunho.POST,
		},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
		MiddlewaresByMethod: map[string][]trilha.MiddlewareFunc{
			"POST": {app_blog_novo_rascunho.MiddlewarePOST},
		},
	})
	a.Register(trilha.Route{
		Pattern: "/blog/ordem",
		Page:    app_blog_ordem.Page,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_blog_ordem.POST,
		},
		Layouts:     []trilha.LayoutFunc{app_blog.Layout, app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/blog/{slug}",
		Page:    app_blog_slug_.Page,
		Methods: map[string]trilha.HandlerFunc{
			"DELETE": app_blog_slug_.DELETE,
			"POST":   app_blog_slug_.POST,
		},
		Layouts:     []trilha.LayoutFunc{app_blog.Layout, app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/docs/{path...}",
		Page:        app_docs_path__.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/documentos",
		Page:        app_documentos.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/documentos/planilha",
		Methods: map[string]trilha.HandlerFunc{
			"GET":  app_documentos_planilha.GET,
			"POST": app_documentos_planilha.POST,
		},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/documentos/resumo",
		Page:        app_documentos_resumo.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/legado",
		Page:    app_legado__legado.Page,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_legado__legado.POST,
		},
		Layouts:     []trilha.LayoutFunc{app_legado_.Layout, app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/legado/apagar",
		Kind:    app_legado_.Kind,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_legado__legado_apagar.POST,
		},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/login",
		Page:    app_login.Page,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_login.POST,
		},
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/mcp",
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_mcp.POST,
		},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/painel",
		Page:    app_painel__painel.Page,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_painel__painel.POST,
		},
		Layouts:     []trilha.LayoutFunc{app_painel_.Layout, app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware, app_painel_.Middleware},
		MiddlewaresByMethod: map[string][]trilha.MiddlewareFunc{
			"POST": {app_painel_.MiddlewarePOST},
		},
	})
	a.Register(trilha.Route{
		Pattern:     "/precos",
		Page:        app_marketing__precos.Page,
		Layouts:     []trilha.LayoutFunc{app_marketing_.Layout, app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/relatorio",
		Page:        app_painel__relatorio.Page,
		Layouts:     []trilha.LayoutFunc{app_painel_.Layout, app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware, app_painel_.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/sobre",
		Page:        app_marketing__sobre.Page,
		Layouts:     []trilha.LayoutFunc{app_marketing_.Layout, app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/tarefas",
		Page:    app_tarefas.Page,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_tarefas.POST,
		},
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/tarefas/tentar",
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_tarefas_tentar.POST,
		},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/tarefas/{id}",
		Page:        app_tarefas_id_.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/webhooks",
		Page:    app_webhooks.Page,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_webhooks.POST,
		},
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app.Middleware},
	})
	return a
}

func main() {
	trilha.Run(newApp())
}
