// Code generated by trilha. DO NOT EDIT.

//go:generate trilha gen

package main

import (
	"embed"

	trilha "github.com/emersonjoe/trilha"
	app "github.com/emersonjoe/trilha/examples/cadastro/app"
	app_api_cidades "github.com/emersonjoe/trilha/examples/cadastro/app/api/cidades"
	app_ficha "github.com/emersonjoe/trilha/examples/cadastro/app/ficha"
)

//go:embed public
var publicFS embed.FS

// newApp builds the application. Tests can call it and use a.Handler().
func newApp() *trilha.App {
	cfg := trilha.ConfigFromEnv()
	cfg.Public = trilha.PublicFS(publicFS, "public")
	a := trilha.New(cfg)
	if err := app.Setup(a); err != nil {
		trilha.Fatal(err)
	}
	a.SetRootLayout(app.Layout)
	a.Register(trilha.Route{
		Pattern: "/",
		Page:    app.Page,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app.POST,
		},
		Layouts: []trilha.LayoutFunc{app.Layout},
	})
	a.Register(trilha.Route{
		Pattern: "/api/cidades",
		Methods: map[string]trilha.HandlerFunc{
			"GET": app_api_cidades.GET,
		},
	})
	a.Register(trilha.Route{
		Pattern: "/ficha",
		Page:    app_ficha.Page,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_ficha.POST,
		},
		Layouts: []trilha.LayoutFunc{app.Layout},
	})
	return a
}

func main() {
	trilha.Run(newApp())
}
