// Code generated by trilha. DO NOT EDIT.

package main

import (
	"embed"

	trilha "github.com/emersonjoe/trilha"
	app "github.com/emersonjoe/trilha/examples/assistente/app"
	app_api_chat "github.com/emersonjoe/trilha/examples/assistente/app/api/chat"
	app_mcp "github.com/emersonjoe/trilha/examples/assistente/app/mcp"
)

//go:embed public
var publicFS embed.FS

// newApp builds the application. Tests can call it and use a.Handler().
func newApp() *trilha.App {
	cfg := trilha.ConfigFromEnv()
	cfg.Public = trilha.PublicFS(publicFS, "public")
	a := trilha.New(cfg)
	if err := app.Setup(a); err != nil {
		trilha.Fatal(err)
	}
	a.SetRootLayout(app.Layout)
	a.Register(trilha.Route{
		Pattern: "/",
		Page:    app.Page,
		Layouts: []trilha.LayoutFunc{app.Layout},
	})
	a.Register(trilha.Route{
		Pattern: "/api/chat",
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_api_chat.POST,
		},
	})
	a.Register(trilha.Route{
		Pattern: "/mcp",
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_mcp.POST,
		},
	})
	return a
}

func main() {
	trilha.Run(newApp())
}
