package islands

import (
	"strconv"
	"strings"
)

// FileName is where trilha gen writes the declarations, next to the modules
// they describe, so an editor finds them without configuration.
const FileName = "public/islands.d.ts"

// Header marks the file as generated, in the same words as trilha_gen.go.
const Header = "// Code generated by trilha gen. DO NOT EDIT."

// TypeScript writes the declaration file: one interface per props struct, the
// map from module path to props, and the island object the loader passes as the
// third argument.
func (r *Result) TypeScript() string {
	var b strings.Builder
	b.WriteString(Header + "\n")
	b.WriteString("// The other side of c.Island: what each module in public/ receives.\n")
	for _, n := range r.Notes {
		b.WriteString("// note: " + n + "\n")
	}
	b.WriteString("\n")

	for _, o := range r.Objects {
		writeDoc(&b, o.Doc, "")
		b.WriteString("export interface " + o.Name + " {\n")
		for _, p := range o.Props {
			writeDoc(&b, p.Doc, "  ")
			opt := ""
			if p.Optional {
				opt = "?"
			}
			b.WriteString("  " + tsKey(p.Name) + opt + ": " + p.Type + ";\n")
		}
		b.WriteString("}\n\n")
	}

	b.WriteString("/** The props of each island, by the module path given to c.Island. */\n")
	b.WriteString("export interface TrilhaIslandProps {\n")
	if len(r.Islands) == 0 {
		b.WriteString("  [src: string]: unknown;\n")
	}
	for _, is := range r.Islands {
		t := is.Type
		if t == "" {
			t = "unknown"
		}
		b.WriteString("  " + strconv.Quote(is.Src) + ": " + t + ";\n")
	}
	b.WriteString("}\n\n")
	b.WriteString(runtime)
	return b.String()
}

func writeDoc(b *strings.Builder, doc, indent string) {
	if doc == "" {
		return
	}
	lines := strings.Split(doc, "\n")
	if len(lines) == 1 {
		b.WriteString(indent + "/** " + lines[0] + " */\n")
		return
	}
	b.WriteString(indent + "/**\n")
	for _, l := range lines {
		b.WriteString(strings.TrimRight(indent+" * "+l, " ") + "\n")
	}
	b.WriteString(indent + " */\n")
}

// tsKey quotes a JSON name that is not a plain identifier.
func tsKey(name string) string {
	for i := 0; i < len(name); i++ {
		c := name[i]
		ok := c == '_' || c == '$' || (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (i > 0 && c >= '0' && c <= '9')
		if !ok {
			return strconv.Quote(name)
		}
	}
	if name == "" {
		return `""`
	}
	return name
}

// runtime describes what the loader in island.go hands the mount function. It
// is written here, not in the app, because it is the framework's contract.
const runtime = `/** The error island.get, island.post and island.send throw when the route said no. */
export interface IslandError extends Error {
  readonly name: "IslandError" | "IslandInvalid";
  /** The HTTP status, or 0 when the island itself refused to send. */
  readonly status: number;
  /** The detail of the problem+json body, when there was one. */
  readonly detail: string;
  readonly body: unknown;
}

/** What a 422 becomes: the same field errors a form would have shown. */
export interface IslandInvalid extends IslandError {
  readonly name: "IslandInvalid";
  readonly fields: Record<string, string>;
}

/** The way back to the server, given to the mount function as its third argument. */
export interface TrilhaIsland {
  /** The CSRF token of this response, the same one every form of the page carries. */
  csrf(): string;
  /** Aborted when the element leaves the page, so a swapped-away island stops writing. */
  readonly signal: AbortSignal;
  get<T = unknown>(url: string): Promise<T>;
  post<T = unknown>(url: string, data?: unknown): Promise<T>;
  send<T = unknown>(method: string, url: string, data?: unknown): Promise<T>;
  /** Replaces a fragment, the way a link with a target does. Defaults to el.id. */
  swap(url: string, id?: string): Promise<boolean>;
}

/** The default export of an island module. */
export type IslandMount<S extends keyof TrilhaIslandProps> = (
  el: HTMLElement,
  props: TrilhaIslandProps[S],
  island: TrilhaIsland,
) => void;
`
