package client

import (
	"sort"
	"strings"
)

// emit writes the file. The runtime — New, the options, the error, do and
// decode — is written literally rather than kept in a package the app would
// have to import: the generated client depends on the standard library and on
// nothing else, so it works in a cron, in a test, in a binary that is not web.
func (b *builder) emit(d *Doc, opt Options, order []string, groups map[string]*group) []byte {
	var o buf
	title := d.Info.Title
	if title == "" {
		title = "the API"
	}
	o.p("// Code generated by trilha client from %s. DO NOT EDIT.", opt.Source)
	o.p("")
	o.p("// Package %s is the Go client of %s %s.", opt.Package, title, d.Info.Version)
	o.p("//")
	o.p("// It is generated from the OpenAPI document, so the compiler is what catches")
	o.p("// the field that changed name. Regenerate with `trilha client`; `--check` in CI")
	o.p("// fails when the document moved and this file did not.")
	o.p("package %s", opt.Package)
	o.p("")
	o.p("import (")
	for _, im := range b.imports(groups) {
		o.p("\t%q", im)
	}
	o.p(")")
	o.p("")
	b.emitRuntime(&o, title)
	b.emitTypes(&o)
	b.emitGroups(&o, order, groups)
	return o.Bytes()
}

// imports is the fixed list minus what this document did not need.
func (b *builder) imports(groups map[string]*group) []string {
	need := map[string]bool{"context": true, "encoding/json": true, "fmt": true, "io": true, "net/http": true, "net/url": true, "strings": true}
	for _, g := range groups {
		for _, m := range g.Methods {
			if m.Upload != "" {
				need["mime/multipart"] = true
			}
			for _, q := range m.Query {
				if strings.HasPrefix(q.Type, "int") || strings.HasPrefix(q.Type, "float") {
					need["strconv"] = true
				}
			}
			if m.Body != "" {
				need["bytes"] = true
			}
		}
	}
	out := make([]string, 0, len(need))
	for k := range need {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// emitRuntime writes the part that does not depend on the document.
func (b *builder) emitRuntime(o *buf, title string) {
	o.p(`// Client is a connection to %s. It is safe for concurrent use.
type Client struct {
	base   string
	http   *http.Client
	header func(context.Context) http.Header
}

// Option configures a Client.
type Option func(*Client)

// WithClient replaces the http.Client — a timeout of your own, a transport with
// mTLS, a recorder in a test.
func WithClient(h *http.Client) Option { return func(c *Client) { c.http = h } }

// WithHeader runs before every request and adds headers to it. It is where the
// credential of the session goes: the client holds no token of its own, so a
// request without a context that carries one goes out unauthenticated.
func WithHeader(fn func(context.Context) http.Header) Option {
	return func(c *Client) { c.header = fn }
}

// New builds a client for a base URL ("https://api.example.com").
func New(base string, opts ...Option) *Client {
	c := &Client{base: strings.TrimSuffix(base, "/"), http: http.DefaultClient}
	for _, o := range opts {
		o(c)
	}
	return c
}

// Error is a response the API refused. Body is what came back, and Detail is
// the sentence inside it when the answer is problem+json (RFC 9457) or the
// {"detail": ...} of a FastAPI.
type Error struct {
	Status int
	Body   []byte
	Detail string
}

func (e *Error) Error() string {
	if e.Detail != "" {
		return fmt.Sprintf("%%s: %%s", http.StatusText(e.Status), e.Detail)
	}
	return fmt.Sprintf("%%s (%%d)", http.StatusText(e.Status), e.Status)
}

// do sends one request and returns the response with the body still open. A
// status outside 2xx is an *Error, and the body is read into it.
func (c *Client) do(ctx context.Context, method, path string, q url.Values, body io.Reader, ctype string) (*http.Response, error) {
	u := c.base + path
	if len(q) > 0 {
		u += "?" + q.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, method, u, body)
	if err != nil {
		return nil, err
	}
	if ctype != "" {
		req.Header.Set("Content-Type", ctype)
	}
	req.Header.Set("Accept", "application/json")
	if c.header != nil {
		for k, vs := range c.header(ctx) {
			for _, v := range vs {
				req.Header.Add(k, v)
			}
		}
	}
	resp, err := c.http.Do(req)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		defer resp.Body.Close()
		b, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
		return nil, &Error{Status: resp.StatusCode, Body: b, Detail: detailOf(b)}
	}
	return resp, nil
}

// call is do plus decoding: out may be nil for an answer with no content.
func (c *Client) call(ctx context.Context, method, path string, q url.Values, body io.Reader, ctype string, out any) error {
	resp, err := c.do(ctx, method, path, q, body, ctype)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if out == nil || resp.StatusCode == http.StatusNoContent {
		_, _ = io.Copy(io.Discard, resp.Body)
		return nil
	}
	return json.NewDecoder(resp.Body).Decode(out)
}

// detailOf pulls the sentence out of an error body without caring which of the
// two shapes it is.
func detailOf(b []byte) string {
	var m struct {
		Detail any    %sjson:"detail"%s
		Title  string %sjson:"title"%s
		Msg    string %sjson:"message"%s
	}
	if json.Unmarshal(b, &m) != nil {
		return ""
	}
	switch d := m.Detail.(type) {
	case string:
		return d
	case []any:
		if len(d) > 0 {
			if s, err := json.Marshal(d[0]); err == nil {
				return string(s)
			}
		}
	}
	if m.Title != "" {
		return m.Title
	}
	return m.Msg
}

// multipartBody streams one file as multipart/form-data: the upload never sits
// in memory, however large it is.
func multipartBody(field, filename string, r io.Reader) (io.Reader, string) {
	pr, pw := io.Pipe()
	mw := multipart.NewWriter(pw)
	go func() {
		fw, err := mw.CreateFormFile(field, filename)
		if err == nil {
			_, err = io.Copy(fw, r)
		}
		if err == nil {
			err = mw.Close()
		}
		pw.CloseWithError(err)
	}()
	return pr, mw.FormDataContentType()
}
`, title, "`", "`", "`", "`", "`", "`")
}

// emitTypes writes the enums and the structs, in the order they were built.
func (b *builder) emitTypes(o *buf) {
	for _, name := range b.eOrder {
		e := b.enums[name]
		if e.Doc != "" {
			o.p("// %s is %s", e.Name, lowerFirst(e.Doc))
		} else {
			o.p("// %s is one of the values the API accepts here.", e.Name)
		}
		o.p("type %s string", e.Name)
		o.p("")
		if len(e.Values) > 0 {
			o.p("const (")
			for _, v := range e.Values {
				o.p("\t%s %s = %q", v.Name, e.Name, v.Value)
			}
			o.p(")")
			o.p("")
		}
	}
	for _, name := range b.order {
		st := b.byName[name]
		if st == nil {
			continue
		}
		if st.Doc != "" {
			o.p("// %s is %s", st.Name, lowerFirst(st.Doc))
		} else {
			o.p("// %s is a schema of the API.", st.Name)
		}
		o.p("type %s struct {", st.Name)
		for _, f := range st.Fields {
			if f.Doc != "" {
				o.p("\t// %s", f.Doc)
			}
			o.p("\t%s %s `%s`", f.Name, f.Type, f.Tag)
		}
		o.p("}")
		o.p("")
	}
}

// emitGroups writes one struct per tag and one method per operation.
func (b *builder) emitGroups(o *buf, order []string, groups map[string]*group) {
	for _, name := range order {
		o.p("// %s is the %s part of the API.", name, name)
		o.p("type %s struct{ c *Client }", name)
		o.p("")
		o.p("// %s returns the %s part of the API.", name, name)
		o.p("func (c *Client) %s() *%s { return &%s{c: c} }", name, name, name)
		o.p("")
		for _, m := range groups[name].Methods {
			b.emitMethod(o, name, m)
		}
	}
}

// emitMethod writes one method.
func (b *builder) emitMethod(o *buf, gName string, m *method) {
	args := []string{"ctx context.Context"}
	for _, pv := range m.PathVars {
		args = append(args, pv.Name+" string")
	}
	if m.Upload != "" {
		args = append(args, "file io.Reader", "filename string")
	}
	if m.Body != "" {
		args = append(args, "body "+m.Body)
	}
	if m.Params != "" {
		args = append(args, "p "+m.Params)
	}
	ret := "error"
	switch {
	case m.Binary:
		ret = "(*http.Response, error)"
	case m.Return != "":
		ret = "(" + m.Return + ", error)"
	}
	// The doc comment starts with the name, as Go wants, and says which request
	// it is — the line whoever is reading the client wants to see.
	if m.Doc != "" {
		o.p("// %s is %s %s: %s", m.Name, m.HTTP, m.Path, lowerFirst(m.Doc))
	} else {
		o.p("// %s is %s %s.", m.Name, m.HTTP, m.Path)
	}
	o.p("func (g *%s) %s(%s) %s {", gName, m.Name, strings.Join(args, ", "), ret)

	// The path: the target is fixed, and what the caller gives only replaces a
	// {segment}, escaped.
	if len(m.PathVars) == 0 {
		o.p("\tpath := %q", m.Path)
	} else {
		expr := ""
		rest := m.Path
		for _, pv := range m.PathVars {
			i := strings.Index(rest, pv.Raw)
			expr += quote(rest[:i]) + " + url.PathEscape(" + pv.Name + ") + "
			rest = rest[i+len(pv.Raw):]
		}
		expr += quote(rest)
		o.p("\tpath := %s", strings.TrimSuffix(expr, ` + ""`))
	}
	if len(m.Query) > 0 {
		o.p("\tq := url.Values{}")
		for _, q := range m.Query {
			o.p("%s", b.queryCode(q))
		}
	} else {
		o.p("\tvar q url.Values")
	}
	// The answer is declared before the body is encoded, because a failure to
	// encode returns it.
	decl := !m.Binary && m.Return != ""
	if decl {
		o.p("\tvar out %s", m.Return)
	}
	body, ctype, assign := "nil", `""`, ":="
	switch {
	case m.Upload != "":
		o.p("\tbody, ctype := multipartBody(%q, filename, file)", m.Upload)
		body, ctype = "body", "ctype"
	case m.Body != "":
		o.p("\tenc, err := json.Marshal(body)")
		o.p("\tif err != nil {")
		o.p("\t\t%s", failure(m))
		o.p("\t}")
		body, ctype, assign = "bytes.NewReader(enc)", `"application/json"`, "="
	}
	switch {
	case m.Binary:
		o.p("\treturn g.c.do(ctx, %q, path, q, %s, %s)", m.HTTP, body, ctype)
	case decl:
		o.p("\terr %s g.c.call(ctx, %q, path, q, %s, %s, &out)", assign, m.HTTP, body, ctype)
		o.p("\treturn out, err")
	default:
		o.p("\treturn g.c.call(ctx, %q, path, q, %s, %s, nil)", m.HTTP, body, ctype)
	}
	o.p("}")
	o.p("")
}

// failure is the early return of a method whose body failed to encode.
func failure(m *method) string {
	switch {
	case m.Binary:
		return "return nil, err"
	case m.Return != "":
		return "return out, err"
	default:
		return "return err"
	}
}

// queryCode writes one query parameter. An optional one that is at its zero
// value is left out, which is what makes the struct usable: the caller fills in
// the two fields it cares about.
func (b *builder) queryCode(q queryParam) string {
	set := func(expr string) string {
		return "\tq.Set(" + quote(q.Wire) + ", " + expr + ")"
	}
	base := "p." + q.Field
	var expr, guard string
	switch {
	case q.Type == "string":
		expr, guard = base, base+` != ""`
	case b.enums[q.Type] != nil:
		expr, guard = "string("+base+")", base+` != ""`
	case q.Type == "bool":
		expr, guard = `"true"`, base
	case strings.HasPrefix(q.Type, "int"):
		expr, guard = "strconv.FormatInt(int64("+base+"), 10)", base+" != 0"
	case strings.HasPrefix(q.Type, "float"):
		expr, guard = "strconv.FormatFloat(float64("+base+"), 'f', -1, 64)", base+" != 0"
	case q.Type == "[]string":
		return "\tfor _, v := range " + base + " {\n\t\tq.Add(" + quote(q.Wire) + ", v)\n\t}"
	case strings.HasPrefix(q.Type, "[]"):
		return "\tfor _, v := range " + base + " {\n\t\tq.Add(" + quote(q.Wire) + ", fmt.Sprint(v))\n\t}"
	default:
		// A defined string type (an enum) or anything else: fmt.Sprint is the
		// honest answer, and the zero value stays out of the URL.
		expr, guard = "fmt.Sprint("+base+")", "fmt.Sprint("+base+`) != ""`
	}
	if q.Required {
		return set(expr)
	}
	return "\tif " + guard + " {\n\t" + set(expr) + "\n\t}"
}

// quote is strconv.Quote without the import.
func quote(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// isUpperLetter is A-Z without the unicode import.
func isUpperLetter(b byte) bool { return b >= 'A' && b <= 'Z' }

// lowerFirst makes a description read as the rest of a doc comment sentence.
func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	// An acronym stays as it is: ID of the thing, not iD of the thing.
	if len(s) > 1 && isUpperLetter(s[0]) && isUpperLetter(s[1]) {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
