package client

import (
	"fmt"
	"sort"
	"strings"
)

// emit writes the file. The runtime — New, the options, the error, do and
// decode — is written literally rather than kept in a package the app would
// have to import: the generated client depends on the standard library and on
// nothing else, so it works in a cron, in a test, in a binary that is not web.
func (b *builder) emit(d *Doc, opt Options, order []string, groups map[string]*group) []byte {
	var o buf
	title := d.Info.Title
	if title == "" {
		title = "the API"
	}
	o.p("// Code generated by trilha client from %s. DO NOT EDIT.", opt.Source)
	o.p("")
	o.p("// Package %s is the Go client of %s %s.", opt.Package, title, d.Info.Version)
	o.p("//")
	o.p("// It is generated from the OpenAPI document, so the compiler is what catches")
	o.p("// the field that changed name. Regenerate with `trilha client`; `--check` in CI")
	o.p("// fails when the document moved and this file did not.")
	o.p("package %s", opt.Package)
	o.p("")
	o.p("import (")
	for _, im := range b.imports(groups) {
		o.p("\t%q", im)
	}
	o.p(")")
	o.p("")
	b.emitRuntime(&o, title, b.needsMultipart(groups))
	b.emitTypes(&o)
	b.emitGroups(&o, order, groups)
	return o.Bytes()
}

// needsMultipart reports whether any operation sends a form: it decides both
// the import and the part of the runtime that uses it.
func (b *builder) needsMultipart(groups map[string]*group) bool {
	for _, g := range groups {
		for _, m := range g.Methods {
			if m.Upload != "" || m.Form != nil {
				return true
			}
		}
	}
	return false
}

// imports is the fixed list minus what this document did not need.
func (b *builder) imports(groups map[string]*group) []string {
	// errors is AsError, strconv is the index inside a validation "loc": both
	// belong to the runtime, so every generated client has them.
	need := map[string]bool{"context": true, "encoding/json": true, "errors": true, "fmt": true, "io": true, "net/http": true, "net/url": true, "strconv": true, "strings": true}
	if b.needsMultipart(groups) {
		need["mime/multipart"] = true
	}
	for _, g := range groups {
		for _, m := range g.Methods {
			if m.Body != "" {
				need["bytes"] = true
			}
		}
	}
	out := make([]string, 0, len(need))
	for k := range need {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// emitRuntime writes the part that does not depend on the document.
func (b *builder) emitRuntime(o *buf, title string, multipart bool) {
	o.p(`// Client is a connection to %s. It is safe for concurrent use.
type Client struct {
	base   string
	http   *http.Client
	header func(context.Context) http.Header
}

// Option configures a Client.
type Option func(*Client)

// WithClient replaces the http.Client — a timeout of your own, a transport with
// mTLS, a recorder in a test.
func WithClient(h *http.Client) Option { return func(c *Client) { c.http = h } }

// WithHeader runs before every request and adds headers to it. It is where the
// credential of the session goes: the client holds no token of its own, so a
// request without a context that carries one goes out unauthenticated.
func WithHeader(fn func(context.Context) http.Header) Option {
	return func(c *Client) { c.header = fn }
}

// New builds a client for a base URL ("https://api.example.com").
func New(base string, opts ...Option) *Client {
	c := &Client{base: strings.TrimSuffix(base, "/"), http: http.DefaultClient}
	for _, o := range opts {
		o(c)
	}
	return c
}

// Error is a response the API refused. Body is what came back, Detail is the
// sentence inside it when the answer is problem+json (RFC 9457) or the
// {"detail": ...} of a FastAPI, and Fields is one message per field when the
// answer is the validation error of a FastAPI — {"detail": [{"loc": [...],
// "msg": "..."}]}. It is nil for anything else.
//
// Fields is a map[string]string so it converts straight to trilha.FieldErrors,
// which is what a form re-rendered with a message next to each input takes:
//
//	if e, ok := AsError(err); ok && e.Status == 422 {
//		return c.Render(page(in, trilha.FieldErrors(e.Fields)))
//	}
type Error struct {
	Status int
	Body   []byte
	Detail string
	Fields map[string]string
}

// AsError is errors.As without the variable: the *Error inside err, when there
// is one.
func AsError(err error) (*Error, bool) {
	var e *Error
	ok := errors.As(err, &e)
	return e, ok
}

func (e *Error) Error() string {
	if e.Detail != "" {
		return fmt.Sprintf("%%s: %%s", http.StatusText(e.Status), e.Detail)
	}
	return fmt.Sprintf("%%s (%%d)", http.StatusText(e.Status), e.Status)
}

// do sends one request and returns the response with the body still open. A
// status outside 2xx is an *Error, and the body is read into it.
func (c *Client) do(ctx context.Context, method, path string, q url.Values, body io.Reader, ctype string) (*http.Response, error) {
	u := c.base + path
	if len(q) > 0 {
		u += "?" + q.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, method, u, body)
	if err != nil {
		return nil, err
	}
	if ctype != "" {
		req.Header.Set("Content-Type", ctype)
	}
	req.Header.Set("Accept", "application/json")
	if c.header != nil {
		for k, vs := range c.header(ctx) {
			for _, v := range vs {
				req.Header.Add(k, v)
			}
		}
	}
	resp, err := c.http.Do(req)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		defer resp.Body.Close()
		b, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
		detail, fields := problemOf(b)
		return nil, &Error{Status: resp.StatusCode, Body: b, Detail: detail, Fields: fields}
	}
	return resp, nil
}

// call is do plus decoding: out may be nil for an answer with no content.
func (c *Client) call(ctx context.Context, method, path string, q url.Values, body io.Reader, ctype string, out any) error {
	resp, err := c.do(ctx, method, path, q, body, ctype)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if out == nil || resp.StatusCode == http.StatusNoContent {
		_, _ = io.Copy(io.Discard, resp.Body)
		return nil
	}
	return json.NewDecoder(resp.Body).Decode(out)
}

// problemOf pulls the sentence out of an error body without caring which of the
// shapes it is, and the per-field messages when the body is the validation
// error of a FastAPI. The sentence is the first message, never the object it
// came in.
func problemOf(b []byte) (string, map[string]string) {
	var m struct {
		Detail any    %sjson:"detail"%s
		Title  string %sjson:"title"%s
		Msg    string %sjson:"message"%s
	}
	if json.Unmarshal(b, &m) != nil {
		return "", nil
	}
	switch d := m.Detail.(type) {
	case string:
		return d, nil
	case []any:
		detail, fields := "", map[string]string{}
		for _, item := range d {
			obj, _ := item.(map[string]any)
			msg, _ := obj["msg"].(string)
			if msg == "" {
				continue
			}
			if detail == "" {
				detail = msg
			}
			if k := fieldKey(obj["loc"]); k != "" {
				if _, seen := fields[k]; !seen {
					fields[k] = msg
				}
			}
		}
		if len(fields) == 0 {
			fields = nil
		}
		if detail == "" && len(d) > 0 {
			// Not the shape we know: say what came, rather than nothing.
			if s, err := json.Marshal(d[0]); err == nil {
				detail = string(s)
			}
		}
		return detail, fields
	}
	if m.Title != "" {
		return m.Title, nil
	}
	return m.Msg, nil
}

// fieldKey turns the "loc" of a FastAPI message into the name of the form
// field: ["body", "email"] is email, ["body", "itens", 0, "valor"] is
// itens.0.valor, and the part that only says where the value travelled — body,
// query, path, header, cookie — is dropped because the form does not have it.
func fieldKey(loc any) string {
	parts, _ := loc.([]any)
	var out []string
	for i, p := range parts {
		var seg string
		switch v := p.(type) {
		case string:
			if i == 0 {
				switch v {
				case "body", "query", "path", "header", "cookie":
					continue
				}
			}
			seg = v
		case float64:
			seg = strconv.FormatInt(int64(v), 10)
		default:
			continue
		}
		out = append(out, seg)
	}
	return strings.Join(out, ".")
}
`, title, "`", "`", "`", "`", "`", "`")
	if !multipart {
		return
	}
	// Only a document with a multipart operation gets the part that sends one.
	// Emitting it always left `mime/multipart` undefined in the client of every
	// API that takes no file — which is most of them — and the file did not
	// compile.
	o.p(`// FilePart is one file of a multipart body: the name it goes under and the
// bytes, which are read while the request is sent.
type FilePart struct {
	Filename string
	Content  io.Reader
}

// formPart is one part of a multipart body: a file when r is set, a form field
// otherwise.
type formPart struct {
	field    string
	filename string
	r        io.Reader
	value    string
}

// multipartBody streams the parts as multipart/form-data: no file ever sits in
// memory, however large it is, and a writer that fails closes the pipe with the
// error instead of hanging the request.
func multipartBody(parts []formPart) (io.Reader, string) {
	pr, pw := io.Pipe()
	mw := multipart.NewWriter(pw)
	go func() {
		var err error
		for _, p := range parts {
			if p.r == nil {
				err = mw.WriteField(p.field, p.value)
			} else {
				var fw io.Writer
				if fw, err = mw.CreateFormFile(p.field, p.filename); err == nil {
					_, err = io.Copy(fw, p.r)
				}
			}
			if err != nil {
				break
			}
		}
		if err == nil {
			err = mw.Close()
		}
		pw.CloseWithError(err)
	}()
	return pr, mw.FormDataContentType()
}
`)
}

// emitForm writes the struct one multipart operation takes. It exists so the
// caller sees every field the form has — the generator used to read one binary
// property and drop the rest, and a client that quietly loses a field is worse
// than no client.
func (b *builder) emitForm(o *buf, f *form) {
	o.p("// %s is the multipart body of the request below.", f.Type)
	o.p("type %s struct {", f.Type)
	for _, p := range f.Parts {
		t := p.Type
		switch {
		case p.File() && p.Many:
			t = "[]FilePart"
		case p.File():
			t = "FilePart"
		}
		line := "	" + p.Field + " " + t
		switch {
		case p.Doc != "":
			line += " // " + lowerFirst(strings.TrimSuffix(p.Doc, "."))
		case !p.Required:
			line += " // optional: it travels only when it is set"
		}
		o.p("%s", line)
	}
	o.p("}")
	o.p("")
}

// emitFormParts writes the lines that turn the struct into parts. An optional
// scalar left at its zero value does not travel, which is the rule the query
// already follows: the server can tell an empty value from no value.
func (b *builder) emitFormParts(o *buf, f *form) {
	o.p("	parts := make([]formPart, 0, %d)", len(f.Parts))
	for _, p := range f.Parts {
		field := "form." + p.Field
		switch {
		case p.File() && p.Many:
			o.p("	for _, f := range %s {", field)
			o.p("		parts = append(parts, formPart{field: %q, filename: f.Filename, r: f.Content})", p.Wire)
			o.p("	}")
		case p.File():
			o.p("	parts = append(parts, formPart{field: %q, filename: %s.Filename, r: %s.Content})", p.Wire, field, field)
		default:
			part := fmt.Sprintf("parts = append(parts, formPart{field: %q, value: %s})", p.Wire, formValue(field, p.Type))
			if p.Required {
				o.p("	%s", part)
				continue
			}
			o.p("	if %s != %s {", field, zeroOf(p.Type))
			o.p("		%s", part)
			o.p("	}")
		}
	}
}

// isEnumName says whether a form field is a named string type, which needs no
// conversion beyond string().
func isEnumName(typ string) bool {
	switch typ {
	case "string", "bool", "int32", "int64", "float32", "float64":
		return false
	}
	return true
}

// formValue is the field as a string on the wire.
func formValue(expr, typ string) string {
	switch typ {
	case "string":
		return expr
	case "bool":
		return "strconv.FormatBool(" + expr + ")"
	case "int32":
		return "strconv.FormatInt(int64(" + expr + "), 10)"
	case "int64":
		return "strconv.FormatInt(" + expr + ", 10)"
	case "float32":
		return "strconv.FormatFloat(float64(" + expr + "), 'f', -1, 32)"
	case "float64":
		return "strconv.FormatFloat(" + expr + ", 'f', -1, 64)"
	}
	return "string(" + expr + ")" // a named enum, which is a string underneath
}

// zeroOf is what an optional field looks like when nobody filled it in.
func zeroOf(typ string) string {
	switch typ {
	case "string":
		return `""`
	case "bool":
		return "false"
	}
	if typ == "int32" || typ == "int64" || typ == "float32" || typ == "float64" {
		return "0"
	}
	return `""`
}

// emitTypes writes the enums and the structs, in the order they were built.
func (b *builder) emitTypes(o *buf) {
	for _, name := range b.eOrder {
		e := b.enums[name]
		if e.Doc != "" {
			o.p("// %s is %s", e.Name, lowerFirst(e.Doc))
		} else {
			o.p("// %s is one of the values the API accepts here.", e.Name)
		}
		o.p("type %s string", e.Name)
		o.p("")
		if len(e.Values) > 0 {
			o.p("const (")
			for _, v := range e.Values {
				o.p("\t%s %s = %q", v.Name, e.Name, v.Value)
			}
			o.p(")")
			o.p("")
		}
	}
	for _, name := range b.order {
		st := b.byName[name]
		if st == nil {
			continue
		}
		if st.Doc != "" {
			o.p("// %s is %s", st.Name, lowerFirst(st.Doc))
		} else {
			o.p("// %s is a schema of the API.", st.Name)
		}
		o.p("type %s struct {", st.Name)
		for _, f := range st.Fields {
			if f.Doc != "" {
				o.p("\t// %s", f.Doc)
			}
			o.p("\t%s %s `%s`", f.Name, f.Type, f.Tag)
		}
		o.p("}")
		o.p("")
	}
}

// emitGroups writes one struct per tag and one method per operation.
func (b *builder) emitGroups(o *buf, order []string, groups map[string]*group) {
	for _, name := range order {
		g := groups[name]
		o.p("// %s is the %s part of the API.", g.Type, g.Name)
		// What the document called this tag, when the Go name is not it: the
		// label is worth reading and the identifier is worth typing, and after
		// an accent falls or a suffix lands they are no longer the same string.
		for _, line := range g.Doc {
			o.p("// %s", line)
		}
		o.p("type %s struct{ c *Client }", g.Type)
		o.p("")
		o.p("// %s returns the %s part of the API.", g.Name, g.Name)
		o.p("func (c *Client) %s() *%s { return &%s{c: c} }", g.Name, g.Type, g.Type)
		o.p("")
		for _, m := range g.Methods {
			// The form comes before the method that takes it: it is the
			// argument, and a reader arriving at the signature has already
			// seen what it holds.
			if m.Form != nil {
				b.emitForm(o, m.Form)
			}
			b.emitMethod(o, g.Type, m)
		}
	}
}

// emitMethod writes one method.
func (b *builder) emitMethod(o *buf, gName string, m *method) {
	args := []string{"ctx context.Context"}
	for _, pv := range m.PathVars {
		args = append(args, pv.Name+" string")
	}
	if m.Upload != "" {
		args = append(args, "file io.Reader", "filename string")
	}
	if m.Form != nil {
		args = append(args, "form "+m.Form.Type)
	}
	if m.Body != "" {
		args = append(args, "body "+m.Body)
	}
	if m.Params != "" {
		args = append(args, "p "+m.Params)
	}
	ret := "error"
	switch {
	case m.Binary:
		ret = "(*http.Response, error)"
	case m.Return != "":
		ret = "(" + m.Return + ", error)"
	}
	// The doc comment starts with the name, as Go wants, and says which request
	// it is — the line whoever is reading the client wants to see.
	if m.Doc != "" {
		o.p("// %s is %s %s: %s", m.Name, m.HTTP, m.Path, lowerFirst(m.Doc))
	} else {
		o.p("// %s is %s %s.", m.Name, m.HTTP, m.Path)
	}
	o.p("func (g *%s) %s(%s) %s {", gName, m.Name, strings.Join(args, ", "), ret)

	// The path: the target is fixed, and what the caller gives only replaces a
	// {segment}, escaped.
	if len(m.PathVars) == 0 {
		o.p("\tpath := %q", m.Path)
	} else {
		expr := ""
		rest := m.Path
		for _, pv := range m.PathVars {
			i := strings.Index(rest, pv.Raw)
			expr += quote(rest[:i]) + " + url.PathEscape(" + pv.Name + ") + "
			rest = rest[i+len(pv.Raw):]
		}
		expr += quote(rest)
		o.p("\tpath := %s", strings.TrimSuffix(expr, ` + ""`))
	}
	if len(m.Query) > 0 {
		o.p("\tq := url.Values{}")
		for _, q := range m.Query {
			o.p("%s", b.queryCode(q))
		}
	} else {
		o.p("\tvar q url.Values")
	}
	// The answer is declared before the body is encoded, because a failure to
	// encode returns it.
	decl := !m.Binary && m.Return != ""
	if decl {
		o.p("\tvar out %s", m.Return)
	}
	body, ctype, assign := "nil", `""`, ":="
	switch {
	case m.Upload != "":
		o.p("\tbody, ctype := multipartBody([]formPart{{field: %q, filename: filename, r: file}})", m.Upload)
		body, ctype = "body", "ctype"
	case m.Form != nil:
		b.emitFormParts(o, m.Form)
		o.p("\tbody, ctype := multipartBody(parts)")
		body, ctype = "body", "ctype"
	case m.Body != "":
		o.p("\tenc, err := json.Marshal(body)")
		o.p("\tif err != nil {")
		o.p("\t\t%s", failure(m))
		o.p("\t}")
		body, ctype, assign = "bytes.NewReader(enc)", `"application/json"`, "="
	}
	switch {
	case m.Binary:
		o.p("\treturn g.c.do(ctx, %q, path, q, %s, %s)", m.HTTP, body, ctype)
	case decl:
		o.p("\terr %s g.c.call(ctx, %q, path, q, %s, %s, &out)", assign, m.HTTP, body, ctype)
		o.p("\treturn out, err")
	default:
		o.p("\treturn g.c.call(ctx, %q, path, q, %s, %s, nil)", m.HTTP, body, ctype)
	}
	o.p("}")
	o.p("")
}

// failure is the early return of a method whose body failed to encode.
func failure(m *method) string {
	switch {
	case m.Binary:
		return "return nil, err"
	case m.Return != "":
		return "return out, err"
	default:
		return "return err"
	}
}

// queryCode writes one query parameter. An optional one that is at its zero
// value is left out, which is what makes the struct usable: the caller fills in
// the two fields it cares about.
func (b *builder) queryCode(q queryParam) string {
	set := func(expr string) string {
		return "\tq.Set(" + quote(q.Wire) + ", " + expr + ")"
	}
	base := "p." + q.Field
	// A pointer is how the document says "this one may be absent" — Pydantic
	// writes every `str | None = None` as anyOf [string, null] — so nil is the
	// parameter left out and anything else is a value the caller chose, the
	// empty string included. What travels is the value behind the pointer:
	// fmt.Sprint of the pointer itself printed the address, which is never "",
	// so the guard was always true and the filter always garbage.
	if inner, ok := strings.CutPrefix(q.Type, "*"); ok {
		if strings.HasPrefix(inner, "[]") {
			// A nullable list — `tags: list[str] | None` — is still a list: one
			// parameter per element, and nil is none of them.
			return "\tif " + base + " != nil {\n\t" + indent(b.repeat(q.Wire, "*"+base, inner)) + "\n\t}"
		}
		return "\tif " + base + " != nil {\n\t" + set(b.queryValue("*"+base, inner)) + "\n\t}"
	}
	var expr, guard string
	switch {
	case q.Type == "string":
		expr, guard = base, base+` != ""`
	case b.enums[q.Type] != nil:
		expr, guard = "string("+base+")", base+` != ""`
	case q.Type == "bool":
		expr, guard = `"true"`, base
	case strings.HasPrefix(q.Type, "int"):
		expr, guard = "strconv.FormatInt(int64("+base+"), 10)", base+" != 0"
	case strings.HasPrefix(q.Type, "float"):
		expr, guard = "strconv.FormatFloat(float64("+base+"), 'f', -1, 64)", base+" != 0"
	case strings.HasPrefix(q.Type, "[]"):
		return b.repeat(q.Wire, base, q.Type)
	default:
		// A defined string type (an enum) or anything else: fmt.Sprint is the
		// honest answer, and the zero value stays out of the URL.
		expr, guard = "fmt.Sprint("+base+")", "fmt.Sprint("+base+`) != ""`
	}
	if q.Required {
		return set(expr)
	}
	return "\tif " + guard + " {\n\t" + set(expr) + "\n\t}"
}

// repeat writes a list as what a list is in a URL: the same name, once per
// element.
func (b *builder) repeat(wire, base, typ string) string {
	elem := strings.TrimPrefix(typ, "[]")
	return "\tfor _, v := range " + base + " {\n\t\tq.Add(" + quote(wire) + ", " + b.queryValue("v", elem) + ")\n\t}"
}

// indent pushes a block one tab in, so a loop nested inside an `if` reads as
// the rest of the generated file does.
func indent(s string) string { return strings.ReplaceAll(s, "\n", "\n\t") }

// queryValue is one value as a string on the wire. It is what a form field
// already does, plus the enum, which in a query is a defined string type.
func (b *builder) queryValue(expr, typ string) string {
	switch typ {
	case "string", "bool", "int32", "int64", "float32", "float64":
		return formValue(expr, typ)
	}
	if b.enums[typ] != nil {
		return "string(" + expr + ")"
	}
	// Anything else — an object somebody put in a query — is what it always
	// was: fmt.Sprint of the value, which at least is the value.
	return "fmt.Sprint(" + expr + ")"
}

// quote is strconv.Quote without the import.
func quote(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		default:
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// isUpperLetter is A-Z without the unicode import.
func isUpperLetter(b byte) bool { return b >= 'A' && b <= 'Z' }

// lowerFirst makes a description read as the rest of a doc comment sentence.
func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	// An acronym stays as it is: ID of the thing, not iD of the thing.
	if len(s) > 1 && isUpperLetter(s[0]) && isUpperLetter(s[1]) {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}
