// Code generated by trilha gen. DO NOT EDIT.
// The other side of c.Island: what each module in public/ receives.
// note: page.go:11: the props of /chart.js are not a struct literal, so its type is unknown; declare a props struct to get one

/** EditorProps is everything the editor needs to take over the textarea. */
export interface EditorProps {
  name: string;
  email?: string;
  /** WPM is the reading speed shown under the counter. */
  wpm: number;
  status: string;
  tags: string[];
  draft?: Revision;
  counts: Record<string, number>;
  raw: string;
  size: { rows: number };
}

/** Revision points at the one before it. */
export interface Revision {
  at: string;
  prev?: Revision;
}

/** The props of each island, by the module path given to c.Island. */
export interface TrilhaIslandProps {
  "/chart.js": unknown;
  "/clock.js": unknown;
  "/editor.js": EditorProps;
}

/** The error island.get, island.post and island.send throw when the route said no. */
export interface IslandError extends Error {
  readonly name: "IslandError" | "IslandInvalid";
  /** The HTTP status, or 0 when the island itself refused to send. */
  readonly status: number;
  /** The detail of the problem+json body, when there was one. */
  readonly detail: string;
  readonly body: unknown;
}

/** What a 422 becomes: the same field errors a form would have shown. */
export interface IslandInvalid extends IslandError {
  readonly name: "IslandInvalid";
  readonly fields: Record<string, string>;
}

/** The way back to the server, given to the mount function as its third argument. */
export interface TrilhaIsland {
  /** The CSRF token of this response, the same one every form of the page carries. */
  csrf(): string;
  /** Aborted when the element leaves the page, so a swapped-away island stops writing. */
  readonly signal: AbortSignal;
  get<T = unknown>(url: string): Promise<T>;
  post<T = unknown>(url: string, data?: unknown): Promise<T>;
  send<T = unknown>(method: string, url: string, data?: unknown): Promise<T>;
  /** Replaces a fragment, the way a link with a target does. Defaults to el.id. */
  swap(url: string, id?: string): Promise<boolean>;
}

/** The default export of an island module. */
export type IslandMount<S extends keyof TrilhaIslandProps> = (
  el: HTMLElement,
  props: TrilhaIslandProps[S],
  island: TrilhaIsland,
) => void;
