// Code generated by trilha client from testdata/openapi/acervo.json. DO NOT EDIT.

// Package api is the Go client of Acervo API 2.4.0.
//
// It is generated from the OpenAPI document, so the compiler is what catches
// the field that changed name. Regenerate with `trilha client`; `--check` in CI
// fails when the document moved and this file did not.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// Client is a connection to Acervo API. It is safe for concurrent use.
type Client struct {
	base   string
	http   *http.Client
	header func(context.Context) http.Header
}

// Option configures a Client.
type Option func(*Client)

// WithClient replaces the http.Client — a timeout of your own, a transport with
// mTLS, a recorder in a test.
func WithClient(h *http.Client) Option { return func(c *Client) { c.http = h } }

// WithHeader runs before every request and adds headers to it. It is where the
// credential of the session goes: the client holds no token of its own, so a
// request without a context that carries one goes out unauthenticated.
func WithHeader(fn func(context.Context) http.Header) Option {
	return func(c *Client) { c.header = fn }
}

// New builds a client for a base URL ("https://api.example.com").
func New(base string, opts ...Option) *Client {
	c := &Client{base: strings.TrimSuffix(base, "/"), http: http.DefaultClient}
	for _, o := range opts {
		o(c)
	}
	return c
}

// Error is a response the API refused. Body is what came back, and Detail is
// the sentence inside it when the answer is problem+json (RFC 9457) or the
// {"detail": ...} of a FastAPI.
type Error struct {
	Status int
	Body   []byte
	Detail string
}

func (e *Error) Error() string {
	if e.Detail != "" {
		return fmt.Sprintf("%s: %s", http.StatusText(e.Status), e.Detail)
	}
	return fmt.Sprintf("%s (%d)", http.StatusText(e.Status), e.Status)
}

// do sends one request and returns the response with the body still open. A
// status outside 2xx is an *Error, and the body is read into it.
func (c *Client) do(ctx context.Context, method, path string, q url.Values, body io.Reader, ctype string) (*http.Response, error) {
	u := c.base + path
	if len(q) > 0 {
		u += "?" + q.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, method, u, body)
	if err != nil {
		return nil, err
	}
	if ctype != "" {
		req.Header.Set("Content-Type", ctype)
	}
	req.Header.Set("Accept", "application/json")
	if c.header != nil {
		for k, vs := range c.header(ctx) {
			for _, v := range vs {
				req.Header.Add(k, v)
			}
		}
	}
	resp, err := c.http.Do(req)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		defer resp.Body.Close()
		b, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
		return nil, &Error{Status: resp.StatusCode, Body: b, Detail: detailOf(b)}
	}
	return resp, nil
}

// call is do plus decoding: out may be nil for an answer with no content.
func (c *Client) call(ctx context.Context, method, path string, q url.Values, body io.Reader, ctype string, out any) error {
	resp, err := c.do(ctx, method, path, q, body, ctype)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if out == nil || resp.StatusCode == http.StatusNoContent {
		_, _ = io.Copy(io.Discard, resp.Body)
		return nil
	}
	return json.NewDecoder(resp.Body).Decode(out)
}

// detailOf pulls the sentence out of an error body without caring which of the
// two shapes it is.
func detailOf(b []byte) string {
	var m struct {
		Detail any    `json:"detail"`
		Title  string `json:"title"`
		Msg    string `json:"message"`
	}
	if json.Unmarshal(b, &m) != nil {
		return ""
	}
	switch d := m.Detail.(type) {
	case string:
		return d
	case []any:
		if len(d) > 0 {
			if s, err := json.Marshal(d[0]); err == nil {
				return string(s)
			}
		}
	}
	if m.Title != "" {
		return m.Title
	}
	return m.Msg
}

// multipartBody streams one file as multipart/form-data: the upload never sits
// in memory, however large it is.
func multipartBody(field, filename string, r io.Reader) (io.Reader, string) {
	pr, pw := io.Pipe()
	mw := multipart.NewWriter(pw)
	go func() {
		fw, err := mw.CreateFormFile(field, filename)
		if err == nil {
			_, err = io.Copy(fw, r)
		}
		if err == nil {
			err = mw.Close()
		}
		pw.CloseWithError(err)
	}()
	return pr, mw.FormDataContentType()
}

// Status is status of a document in the pipeline.
type Status string

const (
	StatusPending    Status = "pending"
	StatusProcessing Status = "processing"
	StatusReady      Status = "ready"
	StatusFailed     Status = "failed"
)

// UserRole is one of the values the API accepts here.
type UserRole string

const (
	UserRoleAdmin  UserRole = "admin"
	UserRoleMember UserRole = "member"
)

// Base is a schema of the API.
type Base struct {
	CreatedAt string `json:"created_at,omitempty"`
	ID        string `json:"id" validate:"required"`
}

// Document is a document the API stores.
type Document struct {
	Archived  bool                       `json:"archived,omitempty"`
	CreatedAt string                     `json:"created_at,omitempty"`
	Filename  string                     `json:"filename" validate:"required,min=1,max=255"`
	ID        string                     `json:"id" validate:"required"`
	Metadata  map[string]json.RawMessage `json:"metadata,omitempty"`
	Pages     int32                      `json:"pages,omitempty"`
	Payload   json.RawMessage            `json:"payload,omitempty"`
	Score     float64                    `json:"score,omitempty"`
	SizeBytes int64                      `json:"size_bytes,omitempty"`
	Status    Status                     `json:"status" validate:"required"`
	Tags      []string                   `json:"tags,omitempty"`
}

// DocumentIn is a schema of the API.
type DocumentIn struct {
	Filename string `json:"filename" validate:"required,min=1"`
	Folder   string `json:"folder,omitempty"`
}

// Folder is a folder, which contains folders.
type Folder struct {
	Children []Folder `json:"children,omitempty"`
	ID       string   `json:"id" validate:"required"`
	Name     string   `json:"name" validate:"required"`
	Parent   *Folder  `json:"parent,omitempty"`
}

// PagedDocument is a page of documents.
type PagedDocument struct {
	Items    []Document `json:"items" validate:"required"`
	Page     int64      `json:"page" validate:"required"`
	PageSize int64      `json:"page_size,omitempty"`
	Pages    int64      `json:"pages,omitempty"`
	Total    int64      `json:"total" validate:"required"`
}

// User is a schema of the API.
type User struct {
	Email string   `json:"email" validate:"required,email"`
	Name  string   `json:"name" validate:"required,min=2"`
	Role  UserRole `json:"role,omitempty" validate:"oneof=admin member"`
	Site  string   `json:"site,omitempty" validate:"url"`
}

// DocumentsListParams is query of GET /api/documents.
type DocumentsListParams struct {
	Archived bool     `json:"archived,omitempty"`
	Page     int64    `json:"page,omitempty" validate:"min=1"`
	PageSize int64    `json:"page_size,omitempty" validate:"max=200"`
	Q        string   `json:"q,omitempty"`
	Status   Status   `json:"status,omitempty"`
	Tag      []string `json:"tag,omitempty"`
}

// DefaultHealthResponse is a schema of the API.
type DefaultHealthResponse struct {
	Checks map[string]string `json:"checks,omitempty"`
	Status string            `json:"status,omitempty"`
}

// Default is the Default part of the API.
type Default struct{ c *Client }

// Default returns the Default part of the API.
func (c *Client) Default() *Default { return &Default{c: c} }

// Health is GET /api/health.
func (g *Default) Health(ctx context.Context) (DefaultHealthResponse, error) {
	path := "/api/health"
	var q url.Values
	var out DefaultHealthResponse
	err := g.c.call(ctx, "GET", path, q, nil, "", &out)
	return out, err
}

// Documents is the Documents part of the API.
type Documents struct{ c *Client }

// Documents returns the Documents part of the API.
func (c *Client) Documents() *Documents { return &Documents{c: c} }

// Create is POST /api/documents: create a document from metadata only.
func (g *Documents) Create(ctx context.Context, body DocumentIn) (Document, error) {
	path := "/api/documents"
	var q url.Values
	var out Document
	enc, err := json.Marshal(body)
	if err != nil {
		return out, err
	}
	err = g.c.call(ctx, "POST", path, q, bytes.NewReader(enc), "application/json", &out)
	return out, err
}

// Delete is DELETE /api/documents/{document_id}.
func (g *Documents) Delete(ctx context.Context, documentID string) error {
	path := "/api/documents/" + url.PathEscape(documentID)
	var q url.Values
	return g.c.call(ctx, "DELETE", path, q, nil, "", nil)
}

// Download is GET /api/documents/{document_id}/file: the bytes of the document.
func (g *Documents) Download(ctx context.Context, documentID string) (*http.Response, error) {
	path := "/api/documents/" + url.PathEscape(documentID) + "/file"
	var q url.Values
	return g.c.do(ctx, "GET", path, q, nil, "")
}

// Get is GET /api/documents/{document_id}.
func (g *Documents) Get(ctx context.Context, documentID string) (Document, error) {
	path := "/api/documents/" + url.PathEscape(documentID)
	var q url.Values
	var out Document
	err := g.c.call(ctx, "GET", path, q, nil, "", &out)
	return out, err
}

// List is GET /api/documents: list documents, newest first.
func (g *Documents) List(ctx context.Context, p DocumentsListParams) (PagedDocument, error) {
	path := "/api/documents"
	q := url.Values{}
	if p.Archived {
		q.Set("archived", "true")
	}
	if p.Page != 0 {
		q.Set("page", strconv.FormatInt(int64(p.Page), 10))
	}
	if p.PageSize != 0 {
		q.Set("page_size", strconv.FormatInt(int64(p.PageSize), 10))
	}
	if p.Q != "" {
		q.Set("q", p.Q)
	}
	if p.Status != "" {
		q.Set("status", string(p.Status))
	}
	for _, v := range p.Tag {
		q.Add("tag", v)
	}
	var out PagedDocument
	err := g.c.call(ctx, "GET", path, q, nil, "", &out)
	return out, err
}

// Upload is POST /api/documents/upload: send a file and let the API read it.
func (g *Documents) Upload(ctx context.Context, file io.Reader, filename string) (Document, error) {
	path := "/api/documents/upload"
	var q url.Values
	var out Document
	body, ctype := multipartBody("upload", filename, file)
	err := g.c.call(ctx, "POST", path, q, body, ctype, &out)
	return out, err
}

// Folders is the Folders part of the API.
type Folders struct{ c *Client }

// Folders returns the Folders part of the API.
func (c *Client) Folders() *Folders { return &Folders{c: c} }

// ListTree is GET /api/folders/{folder_id}/tree.
func (g *Folders) ListTree(ctx context.Context, folderID string) (Folder, error) {
	path := "/api/folders/" + url.PathEscape(folderID) + "/tree"
	var q url.Values
	var out Folder
	err := g.c.call(ctx, "GET", path, q, nil, "", &out)
	return out, err
}

// Users is the Users part of the API.
type Users struct{ c *Client }

// Users returns the Users part of the API.
func (c *Client) Users() *Users { return &Users{c: c} }

// Upsert is PUT /api/users.
func (g *Users) Upsert(ctx context.Context, body User) (User, error) {
	path := "/api/users"
	var q url.Values
	var out User
	enc, err := json.Marshal(body)
	if err != nil {
		return out, err
	}
	err = g.c.call(ctx, "PUT", path, q, bytes.NewReader(enc), "application/json", &out)
	return out, err
}
