// Code generated by trilha. DO NOT EDIT.

package main

import (
	"embed"

	trilha "github.com/emersonjoe/trilha"
	app "github.com/emersonjoe/trilha/examples/orcamento/app"
	app_api_relatorio_csv "github.com/emersonjoe/trilha/examples/orcamento/app/api/relatorio.csv"
	app_contas_codigo_ "github.com/emersonjoe/trilha/examples/orcamento/app/contas/codigo_"
	app_lancamentos "github.com/emersonjoe/trilha/examples/orcamento/app/lancamentos"
)

//go:embed public
var publicFS embed.FS

// newApp builds the application. Tests can call it and use a.Handler().
func newApp() *trilha.App {
	cfg := trilha.ConfigFromEnv()
	cfg.Public = trilha.PublicFS(publicFS, "public")
	a := trilha.New(cfg)
	if err := app.Setup(a); err != nil {
		trilha.Fatal(err)
	}
	a.SetRootLayout(app.Layout)
	a.Register(trilha.Route{
		Pattern: "/",
		Page:    app.Page,
		Layouts: []trilha.LayoutFunc{app.Layout},
	})
	a.Register(trilha.Route{
		Pattern: "/api/relatorio.csv",
		Methods: map[string]trilha.HandlerFunc{
			"GET": app_api_relatorio_csv.GET,
		},
	})
	a.Register(trilha.Route{
		Pattern: "/contas/{codigo}",
		Page:    app_contas_codigo_.Page,
		Layouts: []trilha.LayoutFunc{app.Layout},
	})
	a.Register(trilha.Route{
		Pattern: "/lancamentos",
		Page:    app_lancamentos.Page,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_lancamentos.POST,
		},
		Layouts: []trilha.LayoutFunc{app.Layout},
	})
	return a
}

func main() {
	trilha.Run(newApp())
}
