// Code generated by gen_elements.py; DO NOT EDIT.

package h

// Html renders a <html> element.
func Html(children ...Node) Node { return El("html", children...) }

// Head renders a <head> element.
func Head(children ...Node) Node { return El("head", children...) }

// Body renders a <body> element.
func Body(children ...Node) Node { return El("body", children...) }

// Title renders a <title> element.
func Title(children ...Node) Node { return El("title", children...) }

// Script renders a <script> element.
func Script(children ...Node) Node { return El("script", children...) }

// Style renders a <style> element.
func Style(children ...Node) Node { return El("style", children...) }

// Noscript renders a <noscript> element.
func Noscript(children ...Node) Node { return El("noscript", children...) }

// Div renders a <div> element.
func Div(children ...Node) Node { return El("div", children...) }

// Span renders a <span> element.
func Span(children ...Node) Node { return El("span", children...) }

// P renders a <p> element.
func P(children ...Node) Node { return El("p", children...) }

// A renders a <a> element.
func A(children ...Node) Node { return El("a", children...) }

// Ul renders a <ul> element.
func Ul(children ...Node) Node { return El("ul", children...) }

// Ol renders a <ol> element.
func Ol(children ...Node) Node { return El("ol", children...) }

// Li renders a <li> element.
func Li(children ...Node) Node { return El("li", children...) }

// Dl renders a <dl> element.
func Dl(children ...Node) Node { return El("dl", children...) }

// Dt renders a <dt> element.
func Dt(children ...Node) Node { return El("dt", children...) }

// Dd renders a <dd> element.
func Dd(children ...Node) Node { return El("dd", children...) }

// H1 renders a <h1> element.
func H1(children ...Node) Node { return El("h1", children...) }

// H2 renders a <h2> element.
func H2(children ...Node) Node { return El("h2", children...) }

// H3 renders a <h3> element.
func H3(children ...Node) Node { return El("h3", children...) }

// H4 renders a <h4> element.
func H4(children ...Node) Node { return El("h4", children...) }

// H5 renders a <h5> element.
func H5(children ...Node) Node { return El("h5", children...) }

// H6 renders a <h6> element.
func H6(children ...Node) Node { return El("h6", children...) }

// Header renders a <header> element.
func Header(children ...Node) Node { return El("header", children...) }

// Footer renders a <footer> element.
func Footer(children ...Node) Node { return El("footer", children...) }

// Main renders a <main> element.
func Main(children ...Node) Node { return El("main", children...) }

// Nav renders a <nav> element.
func Nav(children ...Node) Node { return El("nav", children...) }

// Section renders a <section> element.
func Section(children ...Node) Node { return El("section", children...) }

// Article renders a <article> element.
func Article(children ...Node) Node { return El("article", children...) }

// Aside renders a <aside> element.
func Aside(children ...Node) Node { return El("aside", children...) }

// Figure renders a <figure> element.
func Figure(children ...Node) Node { return El("figure", children...) }

// Figcaption renders a <figcaption> element.
func Figcaption(children ...Node) Node { return El("figcaption", children...) }

// Address renders a <address> element.
func Address(children ...Node) Node { return El("address", children...) }

// Form renders a <form> element.
func Form(children ...Node) Node { return El("form", children...) }

// Button renders a <button> element.
func Button(children ...Node) Node { return El("button", children...) }

// Label renders a <label> element.
func Label(children ...Node) Node { return El("label", children...) }

// Select renders a <select> element.
func Select(children ...Node) Node { return El("select", children...) }

// Option renders a <option> element.
func Option(children ...Node) Node { return El("option", children...) }

// Optgroup renders a <optgroup> element.
func Optgroup(children ...Node) Node { return El("optgroup", children...) }

// Textarea renders a <textarea> element.
func Textarea(children ...Node) Node { return El("textarea", children...) }

// Fieldset renders a <fieldset> element.
func Fieldset(children ...Node) Node { return El("fieldset", children...) }

// Legend renders a <legend> element.
func Legend(children ...Node) Node { return El("legend", children...) }

// Datalist renders a <datalist> element.
func Datalist(children ...Node) Node { return El("datalist", children...) }

// Output renders a <output> element.
func Output(children ...Node) Node { return El("output", children...) }

// Progress renders a <progress> element.
func Progress(children ...Node) Node { return El("progress", children...) }

// Meter renders a <meter> element.
func Meter(children ...Node) Node { return El("meter", children...) }

// Table renders a <table> element.
func Table(children ...Node) Node { return El("table", children...) }

// Caption renders a <caption> element.
func Caption(children ...Node) Node { return El("caption", children...) }

// Thead renders a <thead> element.
func Thead(children ...Node) Node { return El("thead", children...) }

// Tbody renders a <tbody> element.
func Tbody(children ...Node) Node { return El("tbody", children...) }

// Tfoot renders a <tfoot> element.
func Tfoot(children ...Node) Node { return El("tfoot", children...) }

// Tr renders a <tr> element.
func Tr(children ...Node) Node { return El("tr", children...) }

// Th renders a <th> element.
func Th(children ...Node) Node { return El("th", children...) }

// Td renders a <td> element.
func Td(children ...Node) Node { return El("td", children...) }

// Colgroup renders a <colgroup> element.
func Colgroup(children ...Node) Node { return El("colgroup", children...) }

// Pre renders a <pre> element.
func Pre(children ...Node) Node { return El("pre", children...) }

// Code renders a <code> element.
func Code(children ...Node) Node { return El("code", children...) }

// Strong renders a <strong> element.
func Strong(children ...Node) Node { return El("strong", children...) }

// Em renders a <em> element.
func Em(children ...Node) Node { return El("em", children...) }

// Small renders a <small> element.
func Small(children ...Node) Node { return El("small", children...) }

// Time renders a <time> element.
func Time(children ...Node) Node { return El("time", children...) }

// Details renders a <details> element.
func Details(children ...Node) Node { return El("details", children...) }

// Summary renders a <summary> element.
func Summary(children ...Node) Node { return El("summary", children...) }

// Dialog renders a <dialog> element.
func Dialog(children ...Node) Node { return El("dialog", children...) }

// Blockquote renders a <blockquote> element.
func Blockquote(children ...Node) Node { return El("blockquote", children...) }

// Q renders a <q> element.
func Q(children ...Node) Node { return El("q", children...) }

// Cite renders a <cite> element.
func Cite(children ...Node) Node { return El("cite", children...) }

// Abbr renders a <abbr> element.
func Abbr(children ...Node) Node { return El("abbr", children...) }

// Mark renders a <mark> element.
func Mark(children ...Node) Node { return El("mark", children...) }

// Sub renders a <sub> element.
func Sub(children ...Node) Node { return El("sub", children...) }

// Sup renders a <sup> element.
func Sup(children ...Node) Node { return El("sup", children...) }

// B renders a <b> element.
func B(children ...Node) Node { return El("b", children...) }

// I renders a <i> element.
func I(children ...Node) Node { return El("i", children...) }

// U renders a <u> element.
func U(children ...Node) Node { return El("u", children...) }

// S renders a <s> element.
func S(children ...Node) Node { return El("s", children...) }

// Kbd renders a <kbd> element.
func Kbd(children ...Node) Node { return El("kbd", children...) }

// Samp renders a <samp> element.
func Samp(children ...Node) Node { return El("samp", children...) }

// Var renders a <var> element.
func Var(children ...Node) Node { return El("var", children...) }

// Del renders a <del> element.
func Del(children ...Node) Node { return El("del", children...) }

// Ins renders a <ins> element.
func Ins(children ...Node) Node { return El("ins", children...) }

// Bdi renders a <bdi> element.
func Bdi(children ...Node) Node { return El("bdi", children...) }

// Bdo renders a <bdo> element.
func Bdo(children ...Node) Node { return El("bdo", children...) }

// Ruby renders a <ruby> element.
func Ruby(children ...Node) Node { return El("ruby", children...) }

// Picture renders a <picture> element.
func Picture(children ...Node) Node { return El("picture", children...) }

// Video renders a <video> element.
func Video(children ...Node) Node { return El("video", children...) }

// Audio renders a <audio> element.
func Audio(children ...Node) Node { return El("audio", children...) }

// Canvas renders a <canvas> element.
func Canvas(children ...Node) Node { return El("canvas", children...) }

// Iframe renders a <iframe> element.
func Iframe(children ...Node) Node { return El("iframe", children...) }

// Object renders a <object> element.
func Object(children ...Node) Node { return El("object", children...) }

// Svg renders a <svg> element.
func Svg(children ...Node) Node { return El("svg", children...) }

// Template renders a <template> element.
func Template(children ...Node) Node { return El("template", children...) }

// Slot renders a <slot> element.
func Slot(children ...Node) Node { return El("slot", children...) }

// Menu renders a <menu> element.
func Menu(children ...Node) Node { return El("menu", children...) }

// Search renders a <search> element.
func Search(children ...Node) Node { return El("search", children...) }

// Meta renders a void <meta> element.
func Meta(attrs ...Node) Node { return Void("meta", attrs...) }

// Link renders a void <link> element.
func Link(attrs ...Node) Node { return Void("link", attrs...) }

// Img renders a void <img> element.
func Img(attrs ...Node) Node { return Void("img", attrs...) }

// Br renders a void <br> element.
func Br(attrs ...Node) Node { return Void("br", attrs...) }

// Hr renders a void <hr> element.
func Hr(attrs ...Node) Node { return Void("hr", attrs...) }

// Input renders a void <input> element.
func Input(attrs ...Node) Node { return Void("input", attrs...) }

// Source renders a void <source> element.
func Source(attrs ...Node) Node { return Void("source", attrs...) }

// Track renders a void <track> element.
func Track(attrs ...Node) Node { return Void("track", attrs...) }

// Wbr renders a void <wbr> element.
func Wbr(attrs ...Node) Node { return Void("wbr", attrs...) }

// Area renders a void <area> element.
func Area(attrs ...Node) Node { return Void("area", attrs...) }

// Col renders a void <col> element.
func Col(attrs ...Node) Node { return Void("col", attrs...) }

// Embed renders a void <embed> element.
func Embed(attrs ...Node) Node { return Void("embed", attrs...) }

// Param renders a void <param> element.
func Param(attrs ...Node) Node { return Void("param", attrs...) }

// Base renders a void <base> element.
func Base(attrs ...Node) Node { return Void("base", attrs...) }
