// Code generated by trilha. DO NOT EDIT.

//go:generate trilha gen

package main

import (
	"embed"

	trilha "github.com/emersonjoe/trilha"
	app "github.com/emersonjoe/trilha/examples/local-login/app"
	app_api_v1 "github.com/emersonjoe/trilha/examples/local-login/app/api/v1"
	app_api_v1_documentos "github.com/emersonjoe/trilha/examples/local-login/app/api/v1/documentos"
	app_auditoria "github.com/emersonjoe/trilha/examples/local-login/app/auditoria"
	app_auditoria_csv "github.com/emersonjoe/trilha/examples/local-login/app/auditoria/csv"
	app_chaves "github.com/emersonjoe/trilha/examples/local-login/app/chaves"
	app_entrar "github.com/emersonjoe/trilha/examples/local-login/app/entrar"
	app_painel "github.com/emersonjoe/trilha/examples/local-login/app/painel"
	app_painel_eventos "github.com/emersonjoe/trilha/examples/local-login/app/painel/eventos"
	app_permissoes "github.com/emersonjoe/trilha/examples/local-login/app/permissoes"
	app_sair "github.com/emersonjoe/trilha/examples/local-login/app/sair"
)

//go:embed public
var publicFS embed.FS

// newApp builds the application. Tests can call it and use a.Handler().
func newApp() *trilha.App {
	cfg := trilha.ConfigFromEnv()
	cfg.Public = trilha.PublicFS(publicFS, "public")
	app.Config(&cfg)
	a := trilha.New(cfg)
	if err := app.Setup(a); err != nil {
		trilha.Fatal(err)
	}
	a.SetRootLayout(app.Layout)
	a.Register(trilha.Route{
		Pattern: "/",
		Page:    app.Page,
		Layouts: []trilha.LayoutFunc{app.Layout},
	})
	a.Register(trilha.Route{
		Pattern: "/api/v1/documentos",
		Kind:    app.Kind,
		Methods: map[string]trilha.HandlerFunc{
			"GET": app_api_v1_documentos.GET,
		},
		Middlewares: []trilha.MiddlewareFunc{app_api_v1.Middleware},
	})
	a.Register(trilha.Route{
		Pattern:     "/auditoria",
		Page:        app_auditoria.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app_auditoria.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/auditoria/csv",
		Kind:    app.Kind,
		Methods: map[string]trilha.HandlerFunc{
			"GET": app_auditoria_csv.GET,
		},
		Middlewares: []trilha.MiddlewareFunc{app_auditoria.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/chaves",
		Page:    app_chaves.Page,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_chaves.POST,
		},
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app_chaves.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/entrar",
		Page:    app_entrar.Page,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_entrar.POST,
		},
		Layouts: []trilha.LayoutFunc{app.Layout},
	})
	a.Register(trilha.Route{
		Pattern:     "/painel",
		Page:        app_painel.Page,
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app_painel.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/painel/eventos",
		Kind:    app.Kind,
		Methods: map[string]trilha.HandlerFunc{
			"GET": app_painel_eventos.GET,
		},
		Middlewares: []trilha.MiddlewareFunc{app_painel.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/permissoes",
		Page:    app_permissoes.Page,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_permissoes.POST,
		},
		Layouts:     []trilha.LayoutFunc{app.Layout},
		Middlewares: []trilha.MiddlewareFunc{app_permissoes.Middleware},
	})
	a.Register(trilha.Route{
		Pattern: "/sair",
		Kind:    app.Kind,
		Methods: map[string]trilha.HandlerFunc{
			"POST": app_sair.POST,
		},
	})
	return a
}

func main() {
	trilha.Run(newApp())
}
