// Code generated by trilha client from openapi.json. DO NOT EDIT.

// Package acervo is the Go client of Acervo API 1.0.0.
//
// It is generated from the OpenAPI document, so the compiler is what catches
// the field that changed name. Regenerate with `trilha client`; `--check` in CI
// fails when the document moved and this file did not.
package acervo

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// Client is a connection to Acervo API. It is safe for concurrent use.
type Client struct {
	base   string
	http   *http.Client
	header func(context.Context) http.Header
}

// Option configures a Client.
type Option func(*Client)

// WithClient replaces the http.Client — a timeout of your own, a transport with
// mTLS, a recorder in a test.
func WithClient(h *http.Client) Option { return func(c *Client) { c.http = h } }

// WithHeader runs before every request and adds headers to it. It is where the
// credential of the session goes: the client holds no token of its own, so a
// request without a context that carries one goes out unauthenticated.
func WithHeader(fn func(context.Context) http.Header) Option {
	return func(c *Client) { c.header = fn }
}

// New builds a client for a base URL ("https://api.example.com").
func New(base string, opts ...Option) *Client {
	c := &Client{base: strings.TrimSuffix(base, "/"), http: http.DefaultClient}
	for _, o := range opts {
		o(c)
	}
	return c
}

// Error is a response the API refused. Body is what came back, Detail is the
// sentence inside it when the answer is problem+json (RFC 9457) or the
// {"detail": ...} of a FastAPI, and Fields is one message per field when the
// answer is the validation error of a FastAPI — {"detail": [{"loc": [...],
// "msg": "..."}]}. It is nil for anything else.
//
// Fields is a map[string]string so it converts straight to trilha.FieldErrors,
// which is what a form re-rendered with a message next to each input takes:
//
//	if e, ok := AsError(err); ok && e.Status == 422 {
//		return c.Render(page(in, trilha.FieldErrors(e.Fields)))
//	}
type Error struct {
	Status int
	Body   []byte
	Detail string
	Fields map[string]string
}

// AsError is errors.As without the variable: the *Error inside err, when there
// is one.
func AsError(err error) (*Error, bool) {
	var e *Error
	ok := errors.As(err, &e)
	return e, ok
}

func (e *Error) Error() string {
	if e.Detail != "" {
		return fmt.Sprintf("%s: %s", http.StatusText(e.Status), e.Detail)
	}
	return fmt.Sprintf("%s (%d)", http.StatusText(e.Status), e.Status)
}

// do sends one request and returns the response with the body still open. A
// status outside 2xx is an *Error, and the body is read into it.
func (c *Client) do(ctx context.Context, method, path string, q url.Values, body io.Reader, ctype string) (*http.Response, error) {
	u := c.base + path
	if len(q) > 0 {
		u += "?" + q.Encode()
	}
	req, err := http.NewRequestWithContext(ctx, method, u, body)
	if err != nil {
		return nil, err
	}
	if ctype != "" {
		req.Header.Set("Content-Type", ctype)
	}
	req.Header.Set("Accept", "application/json")
	if c.header != nil {
		for k, vs := range c.header(ctx) {
			for _, v := range vs {
				req.Header.Add(k, v)
			}
		}
	}
	resp, err := c.http.Do(req)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode < 200 || resp.StatusCode > 299 {
		defer resp.Body.Close()
		b, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
		detail, fields := problemOf(b)
		return nil, &Error{Status: resp.StatusCode, Body: b, Detail: detail, Fields: fields}
	}
	return resp, nil
}

// call is do plus decoding: out may be nil for an answer with no content.
func (c *Client) call(ctx context.Context, method, path string, q url.Values, body io.Reader, ctype string, out any) error {
	resp, err := c.do(ctx, method, path, q, body, ctype)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if out == nil || resp.StatusCode == http.StatusNoContent {
		_, _ = io.Copy(io.Discard, resp.Body)
		return nil
	}
	return json.NewDecoder(resp.Body).Decode(out)
}

// problemOf pulls the sentence out of an error body without caring which of the
// shapes it is, and the per-field messages when the body is the validation
// error of a FastAPI. The sentence is the first message, never the object it
// came in.
func problemOf(b []byte) (string, map[string]string) {
	var m struct {
		Detail any    `json:"detail"`
		Title  string `json:"title"`
		Msg    string `json:"message"`
	}
	if json.Unmarshal(b, &m) != nil {
		return "", nil
	}
	switch d := m.Detail.(type) {
	case string:
		return d, nil
	case []any:
		detail, fields := "", map[string]string{}
		for _, item := range d {
			obj, _ := item.(map[string]any)
			msg, _ := obj["msg"].(string)
			if msg == "" {
				continue
			}
			if detail == "" {
				detail = msg
			}
			if k := fieldKey(obj["loc"]); k != "" {
				if _, seen := fields[k]; !seen {
					fields[k] = msg
				}
			}
		}
		if len(fields) == 0 {
			fields = nil
		}
		if detail == "" && len(d) > 0 {
			// Not the shape we know: say what came, rather than nothing.
			if s, err := json.Marshal(d[0]); err == nil {
				detail = string(s)
			}
		}
		return detail, fields
	}
	if m.Title != "" {
		return m.Title, nil
	}
	return m.Msg, nil
}

// fieldKey turns the "loc" of a FastAPI message into the name of the form
// field: ["body", "email"] is email, ["body", "itens", 0, "valor"] is
// itens.0.valor, and the part that only says where the value travelled — body,
// query, path, header, cookie — is dropped because the form does not have it.
func fieldKey(loc any) string {
	parts, _ := loc.([]any)
	var out []string
	for i, p := range parts {
		var seg string
		switch v := p.(type) {
		case string:
			if i == 0 {
				switch v {
				case "body", "query", "path", "header", "cookie":
					continue
				}
			}
			seg = v
		case float64:
			seg = strconv.FormatInt(int64(v), 10)
		default:
			continue
		}
		out = append(out, seg)
	}
	return strings.Join(out, ".")
}

// Status is where the document is in the pipeline.
type Status string

const (
	StatusPending   Status = "pending"
	StatusProcessed Status = "processed"
	StatusFailed    Status = "failed"
)

// Document is a schema of the API.
type Document struct {
	Filename string `json:"filename" validate:"required"`
	ID       string `json:"id" validate:"required"`
	// Who uploaded it.
	Owner  string `json:"owner,omitempty"`
	Pages  int64  `json:"pages" validate:"required"`
	Status Status `json:"status" validate:"required"`
}

// PagedDocument is a schema of the API.
type PagedDocument struct {
	Items []Document `json:"items" validate:"required"`
	Page  int64      `json:"page,omitempty"`
	Total int64      `json:"total" validate:"required"`
}

// DocumentsListParams is query of GET /api/documents.
type DocumentsListParams struct {
	Page     int64  `json:"page,omitempty" validate:"min=1"`
	PageSize int64  `json:"page_size,omitempty" validate:"max=200"`
	Q        string `json:"q,omitempty"`
}

// Documents is the Documents part of the API.
type Documents struct{ c *Client }

// Documents returns the Documents part of the API.
func (c *Client) Documents() *Documents { return &Documents{c: c} }

// Get is GET /api/documents/{document_id}: one document.
func (g *Documents) Get(ctx context.Context, documentID string) (Document, error) {
	path := "/api/documents/" + url.PathEscape(documentID)
	var q url.Values
	var out Document
	err := g.c.call(ctx, "GET", path, q, nil, "", &out)
	return out, err
}

// List is GET /api/documents: list documents, newest first.
func (g *Documents) List(ctx context.Context, p DocumentsListParams) (PagedDocument, error) {
	path := "/api/documents"
	q := url.Values{}
	if p.Page != 0 {
		q.Set("page", strconv.FormatInt(int64(p.Page), 10))
	}
	if p.PageSize != 0 {
		q.Set("page_size", strconv.FormatInt(int64(p.PageSize), 10))
	}
	if p.Q != "" {
		q.Set("q", p.Q)
	}
	var out PagedDocument
	err := g.c.call(ctx, "GET", path, q, nil, "", &out)
	return out, err
}
