package scaffold

// texts holds the user-visible strings of the generated project, per language.
var texts = map[string]map[string]string{
	"en": {
		"html_lang":   "en",
		"home":        "Home",
		"hello":       "Hello, ",
		"edit":        "Edit app/page.go and save: this page reloads on its own.",
		"routes":      "Routes",
		"routes_desc": "Folders in app/ become URLs.",
		"routes_body": "Create app/about/page.go to answer /about, or app/api/x/route.go for an API.",
		"see_hello":   "See /api/hello",
		"ui":          "UI",
		"ui_desc":     "ui kit: edit public/ui.theme.css to change the colors.",
		"your_name":   "Your name",
		"ui_help":     "Typed components in Go, no JavaScript required.",
		"primary":     "Primary",
		"secondary":   "Secondary",
		"new":         "new",
		"not_found":   "Not found",
		// generate: the comments of a skeleton with a contract
		"gen_input_route": "is what this route receives; the tags are the contract.",
		"gen_input_form":  "is what the form sends; the tags are the contract.",
		"gen_bind":        "Bind validates by the tags: returning its error is the 422 with the fields.",
		"gen_page_form":   "renders the form.",
		"gen_post_form":   "handles the form: 422 with the messages beside the fields, or redirect.",
		"gen_redirect":    "POST \u2192 redirect \u2192 GET: reloading does not send the form again.",
		"gen_submit":      "Send",
		"gen_layout":      "wraps every page in this folder and below.",
		"gen_no_control":  "no control for this type in the skeleton; write the field by hand.",
		"gen_test_route":  "exercises every method the route answers.",
		"gen_test_page":   "renders the page and looks at the node, which survives a change of layout.",
		"nf_lead":         "Page not found.",
	},
	"pt": {
		"html_lang":   "pt-BR",
		"home":        "Início",
		"hello":       "Olá, ",
		"edit":        "Edite app/page.go e salve: esta página recarrega sozinha.",
		"routes":      "Rotas",
		"routes_desc": "Pastas em app/ viram URLs.",
		"routes_body": "Crie app/sobre/page.go para responder /sobre, ou app/api/x/route.go para uma API.",
		"see_hello":   "Ver /api/hello",
		"ui":          "Interface",
		"ui_desc":     "Kit ui: edite public/ui.theme.css para trocar as cores.",
		"your_name":   "Seu nome",
		"ui_help":     "Componentes tipados em Go, sem JavaScript obrigatório.",
		"primary":     "Primário",
		"secondary":   "Secundário",
		"new":         "novo",
		"not_found":   "Não encontrado",
		// generate: os comentários do esqueleto com contrato
		"gen_input_route": "é o que esta rota recebe; as tags são o contrato.",
		"gen_input_form":  "é o que o formulário manda; as tags são o contrato.",
		"gen_bind":        "O Bind valida pelas tags: devolver o erro dele é o 422 com os campos.",
		"gen_page_form":   "desenha o formulário.",
		"gen_post_form":   "trata o formulário: 422 com as mensagens ao lado dos campos, ou redirect.",
		"gen_redirect":    "POST \u2192 redirect \u2192 GET: recarregar não manda o formulário de novo.",
		"gen_submit":      "Enviar",
		"gen_layout":      "envolve toda página desta pasta para baixo.",
		"gen_no_control":  "o esqueleto não tem controle para este tipo; escreva o campo à mão.",
		"gen_test_route":  "exercita cada método que a rota responde.",
		"gen_test_page":   "desenha a página e olha o nó, que sobrevive a troca de layout.", "nf_lead": "Página não encontrada.",
	},
}
