package scaffold

// texts holds the user-visible strings of the generated project, per language.
var texts = map[string]map[string]string{
	"en": {
		"html_lang":   "en",
		"home":        "Home",
		"hello":       "Hello, ",
		"edit":        "Edit app/page.go and save: this page reloads on its own.",
		"routes":      "Routes",
		"routes_desc": "Folders in app/ become URLs.",
		"routes_body": "Create app/about/page.go to answer /about, or app/api/x/route.go for an API.",
		"see_hello":   "See /api/hello",
		"ui":          "UI",
		"ui_desc":     "ui kit: edit public/ui.theme.css to change the colors.",
		"your_name":   "Your name",
		"ui_help":     "Typed components in Go, no JavaScript required.",
		"primary":     "Primary",
		"secondary":   "Secondary",
		"new":         "new",
		"not_found":   "Not found",
		// generate: the comments of a skeleton with a contract
		"gen_input_route": "is what this route receives; the tags are the contract.",
		"gen_input_form":  "is what the form sends; the tags are the contract.",
		"gen_bind":        "Bind validates by the tags: returning its error is the 422 with the fields.",
		"gen_page_form":   "renders the form.",
		"gen_post_form":   "handles the form: 422 with the messages beside the fields, or redirect.",
		"gen_redirect":    "POST \u2192 redirect \u2192 GET: reloading does not send the form again.",
		"gen_submit":      "Send",
		"gen_layout":      "wraps every page in this folder and below.",
		"gen_no_control":  "no control for this type in the skeleton; write the field by hand.",
		"gen_test_route":  "exercises every method the route answers.",
		"gen_test_page":   "renders the page and looks at the node, which survives a change of layout.",
		"nf_lead":         "Page not found.",
		// app template: the strings of the management skeleton
		"app_seed_email":      "admin@example.com",
		"app_seed_password":   "trilha-demo",
		"app_seed_name":       "Admin",
		"app_seed_hint":       "Seeded account: admin@example.com / trilha-demo",
		"app_currency":        "$",
		"app_decimal":         ".",
		"app_thousands":       ",",
		"app_open":            "Open",
		"app_hold":            "On hold",
		"app_done":            "Done",
		"app_menu_work":       "Work",
		"app_menu_admin":      "Admin",
		"app_dashboard":       "Dashboard",
		"app_items":           "Items",
		"app_new_item":        "New item",
		"app_edit_item":       "Edit item",
		"app_login":           "Sign in",
		"app_logout":          "Sign out",
		"app_email":           "E-mail",
		"app_password":        "Password",
		"app_bad_credentials": "E-mail or password does not match.",
		"app_no_access_title": "No access",
		"app_no_access":       "This area is for administrators.",
		"app_error_title":     "Something went wrong",
		"app_error_id":        "Give this code to whoever looks at the logs:",
		"app_name":            "Name",
		"app_status":          "Status",
		"app_amount":          "Amount",
		"app_amount_total":    "Total amount",
		"app_all":             "All",
		"app_by_status":       "By status",
		"app_search":          "Search",
		"app_empty":           "Nothing here yet.",
		"app_save":            "Save",
		"app_delete":          "Delete",
		"app_delete_q":        "Delete this item?",
		"app_delete_desc":     "This cannot be undone.",
		"app_saved":           "Saved.",
		"app_deleted":         "Deleted.",
		"app_bad_id":          "Item not found.",
		"app_bad_amount":      "Amount must be a number, like 12.50.",
		"app_fix_fields":      "Check the fields below.",
	},
	"pt": {
		"html_lang":   "pt-BR",
		"home":        "Início",
		"hello":       "Olá, ",
		"edit":        "Edite app/page.go e salve: esta página recarrega sozinha.",
		"routes":      "Rotas",
		"routes_desc": "Pastas em app/ viram URLs.",
		"routes_body": "Crie app/sobre/page.go para responder /sobre, ou app/api/x/route.go para uma API.",
		"see_hello":   "Ver /api/hello",
		"ui":          "Interface",
		"ui_desc":     "Kit ui: edite public/ui.theme.css para trocar as cores.",
		"your_name":   "Seu nome",
		"ui_help":     "Componentes tipados em Go, sem JavaScript obrigatório.",
		"primary":     "Primário",
		"secondary":   "Secundário",
		"new":         "novo",
		"not_found":   "Não encontrado",
		// generate: os comentários do esqueleto com contrato
		"gen_input_route": "é o que esta rota recebe; as tags são o contrato.",
		"gen_input_form":  "é o que o formulário manda; as tags são o contrato.",
		"gen_bind":        "O Bind valida pelas tags: devolver o erro dele é o 422 com os campos.",
		"gen_page_form":   "desenha o formulário.",
		"gen_post_form":   "trata o formulário: 422 com as mensagens ao lado dos campos, ou redirect.",
		"gen_redirect":    "POST \u2192 redirect \u2192 GET: recarregar não manda o formulário de novo.",
		"gen_submit":      "Enviar",
		"gen_layout":      "envolve toda página desta pasta para baixo.",
		"gen_no_control":  "o esqueleto não tem controle para este tipo; escreva o campo à mão.",
		"gen_test_route":  "exercita cada método que a rota responde.",
		"gen_test_page":   "desenha a página e olha o nó, que sobrevive a troca de layout.", "nf_lead": "Página não encontrada.",
		// template app: as palavras do esqueleto de gestão
		"app_seed_email":      "admin@exemplo.com",
		"app_seed_password":   "trilha-demo",
		"app_seed_name":       "Admin",
		"app_seed_hint":       "Conta de exemplo: admin@exemplo.com / trilha-demo",
		"app_currency":        "R$",
		"app_decimal":         ",",
		"app_thousands":       ".",
		"app_open":            "Aberto",
		"app_hold":            "Em espera",
		"app_done":            "Pronto",
		"app_menu_work":       "Trabalho",
		"app_menu_admin":      "Administração",
		"app_dashboard":       "Painel",
		"app_items":           "Itens",
		"app_new_item":        "Novo item",
		"app_edit_item":       "Editar item",
		"app_login":           "Entrar",
		"app_logout":          "Sair",
		"app_email":           "E-mail",
		"app_password":        "Senha",
		"app_bad_credentials": "E-mail ou senha não confere.",
		"app_no_access_title": "Sem acesso",
		"app_no_access":       "Esta área é de administradores.",
		"app_error_title":     "Algo deu errado",
		"app_error_id":        "Passe este código a quem olha os logs:",
		"app_name":            "Nome",
		"app_status":          "Situação",
		"app_amount":          "Valor",
		"app_amount_total":    "Valor total",
		"app_all":             "Todos",
		"app_by_status":       "Por situação",
		"app_search":          "Buscar",
		"app_empty":           "Ainda não há nada aqui.",
		"app_save":            "Salvar",
		"app_delete":          "Excluir",
		"app_delete_q":        "Excluir este item?",
		"app_delete_desc":     "Isto não tem volta.",
		"app_saved":           "Salvo.",
		"app_deleted":         "Excluído.",
		"app_bad_id":          "Item não encontrado.",
		"app_bad_amount":      "O valor precisa ser um número, como 12,50.",
		"app_fix_fields":      "Confira os campos abaixo.",
	},
}
