// Code generated by trilha gen. DO NOT EDIT.
// The other side of c.Island: what each module in public/ receives.

/**
 * EditorProps is what the editor island gets. It is a struct, not a map, so
 * `trilha gen` can write public/islands.d.ts and the editor on the JavaScript
 * side knows the same names the page does.
 */
export interface EditorProps {
  /** PalavrasPorMinuto is the reading speed the counter divides by. */
  palavrasPorMinuto: number;
  /** Rascunho is where the island saves without leaving the page. */
  rascunho: string;
}

/**
 * OrdemProps is what the ordering island gets. It is a struct, not a map, so
 * `trilha gen` can write it into public/islands.d.ts and the module on the
 * JavaScript side knows the same names the page does.
 */
export interface OrdemProps {
  /** Ordem is the order the server rendered, slug by slug. */
  ordem: string[];
}

/** The props of each island, by the module path given to c.Island. */
export interface TrilhaIslandProps {
  "/ilha-editor.js": EditorProps;
  "/ilha-ordem.js": OrdemProps;
}

/** The error island.get, island.post and island.send throw when the route said no. */
export interface IslandError extends Error {
  readonly name: "IslandError" | "IslandInvalid";
  /** The HTTP status, or 0 when the island itself refused to send. */
  readonly status: number;
  /** The detail of the problem+json body, when there was one. */
  readonly detail: string;
  readonly body: unknown;
}

/** What a 422 becomes: the same field errors a form would have shown. */
export interface IslandInvalid extends IslandError {
  readonly name: "IslandInvalid";
  readonly fields: Record<string, string>;
}

/** The way back to the server, given to the mount function as its third argument. */
export interface TrilhaIsland {
  /** The CSRF token of this response, the same one every form of the page carries. */
  csrf(): string;
  /** Aborted when the element leaves the page, so a swapped-away island stops writing. */
  readonly signal: AbortSignal;
  get<T = unknown>(url: string): Promise<T>;
  post<T = unknown>(url: string, data?: unknown): Promise<T>;
  send<T = unknown>(method: string, url: string, data?: unknown): Promise<T>;
  /** Replaces a fragment, the way a link with a target does. Defaults to el.id. */
  swap(url: string, id?: string): Promise<boolean>;
}

/** The default export of an island module. */
export type IslandMount<S extends keyof TrilhaIslandProps> = (
  el: HTMLElement,
  props: TrilhaIslandProps[S],
  island: TrilhaIsland,
) => void;
