// Code generated by trilha. DO NOT EDIT.

//go:generate trilha gen

package crm

import (
	trilha "github.com/emersonjoe/trilha"
	app "github.com/emersonjoe/trilha/examples/cookbook/crm/app"
	app_contacts "github.com/emersonjoe/trilha/examples/cookbook/crm/app/contacts"
)

// NewApp builds the application. The host binary calls it and mounts the
// result: mux.Handle("/", NewApp().Handler()).
func NewApp() *trilha.App {
	cfg := trilha.ConfigFromEnv()
	cfg.Public = trilha.PublicFS(nil, "public")
	app.Config(&cfg)
	a := trilha.New(cfg)
	if err := app.Setup(a); err != nil {
		trilha.Fatal(err)
	}
	a.Register(trilha.Route{
		Pattern: "/contacts",
		Page:    app_contacts.Page,
	})
	return a
}
