package ui

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/emersonjoe/trilha/internal/uidoc"
)

// patternDir is where a pattern's page.go lives: the name without hyphens,
// because a Go package cannot have one.
func patternDir(name string) string {
	return filepath.Join("..", "examples", "patterns", strings.ReplaceAll(name, "-", ""), "page.go")
}

// TestPatternSnippetsCurrent keeps patterns_snippets.go equal to the files in
// examples/patterns: the files are the source, because they compile. With
// -update (make golden) it rewrites the generated file.
func TestPatternSnippetsCurrent(t *testing.T) {
	var b bytes.Buffer
	b.WriteString("// Code generated by TestPatternSnippetsCurrent -update from examples/patterns; DO NOT EDIT.\n\npackage ui\n\n")
	b.WriteString("// patternSnippets is every pattern's page.go, by name.\nvar patternSnippets = map[string]string{\n")
	names := make([]string, 0, len(patterns))
	for _, p := range patterns {
		names = append(names, p.Name)
	}
	sort.Strings(names)
	for _, name := range names {
		src, err := os.ReadFile(patternDir(name))
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		fmt.Fprintf(&b, "\t%q: %q,\n", name, string(src))
	}
	b.WriteString("}\n")
	want, err := format.Source(b.Bytes())
	if err != nil {
		t.Fatal(err)
	}
	if *update {
		if err := os.WriteFile("patterns_snippets.go", want, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	got, err := os.ReadFile("patterns_snippets.go")
	if err != nil || !bytes.Equal(got, want) {
		t.Fatal("patterns_snippets.go is out of date with examples/patterns: run make golden")
	}
}

// TestPatternsCompile builds the snippets the way somebody pasting one would:
// every page.go is a package that compiles against this module.
func TestPatternsCompile(t *testing.T) {
	if _, err := exec.LookPath("go"); err != nil {
		t.Skip("go not in PATH")
	}
	cmd := exec.Command("go", "build", "./examples/patterns/...")
	cmd.Dir = ".."
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("go build ./examples/patterns/...: %v\n%s", err, out)
	}
	for _, p := range Patterns() {
		if !strings.Contains(p.Snippet, "\nfunc Page(c *trilha.Ctx) (h.Node, error)") {
			t.Errorf("%s: the snippet is not a page.go — no Page", p.Name)
		}
	}
}

// TestPatternSnippetBudget is the reading budget: a snippet is at most 60
// lines, package clause and imports included.
func TestPatternSnippetBudget(t *testing.T) {
	for _, p := range Patterns() {
		if n := strings.Count(strings.TrimRight(p.Snippet, "\n"), "\n") + 1; n > 60 {
			t.Errorf("%s: %d lines, the budget is 60", p.Name, n)
		}
	}
}

// TestPatternsNameRealComponents holds each pattern to the catalog: every
// component it names exists in `trilha ui components --json`, and the snippet
// actually calls it — a list that drifts from the code is a list that lies.
func TestPatternsNameRealComponents(t *testing.T) {
	seen := map[string]bool{}
	for _, p := range Patterns() {
		if seen[p.Name] || !regexp.MustCompile(`^[a-z]+(-[a-z]+)*$`).MatchString(p.Name) {
			t.Errorf("bad or repeated name %q", p.Name)
		}
		seen[p.Name] = true
		if p.Summary == "" || p.Data == "" || len(p.A11y) == 0 || len(p.Components) == 0 {
			t.Errorf("%s: a field is empty", p.Name)
		}
		for _, name := range p.Components {
			if _, ok := uidoc.Lookup(name); !ok {
				t.Errorf("%s: %s is not in the catalog", p.Name, name)
			}
			if !regexp.MustCompile(`\bui\.` + name + `\b`).MatchString(p.Snippet) {
				t.Errorf("%s: names %s but the snippet never uses ui.%s", p.Name, name, name)
			}
		}
	}
	if len(seen) != 6 {
		t.Fatalf("%d patterns, the plan names six", len(seen))
	}
}

// TestPatternsKeepProtections is the security review a snippet gets, because
// a snippet is what gets copied: every form that writes carries the CSRF
// token, and nothing bypasses the escaping.
func TestPatternsKeepProtections(t *testing.T) {
	for _, p := range Patterns() {
		if strings.Contains(p.Snippet, `h.Method("post")`) && !strings.Contains(p.Snippet, "trilha.CSRFInput(c)") {
			t.Errorf("%s: a POST form without trilha.CSRFInput", p.Name)
		}
		for _, banned := range []string{"h.Raw(", "NoNavigate(", "CSRFForAPI"} {
			if strings.Contains(p.Snippet, banned) {
				t.Errorf("%s: the snippet uses %s", p.Name, banned)
			}
		}
	}
}

// Patterns hands out copies: a caller that edits what it got does not edit
// the next caller's answer.
func TestPatternsAreCopies(t *testing.T) {
	first := Patterns()
	first[0].Components[0] = "changed"
	first[0].A11y[0] = "changed"
	if again := Patterns(); again[0].Components[0] == "changed" || again[0].A11y[0] == "changed" {
		t.Fatal("Patterns shares its slices")
	}
}
