// Code generated by trilha. DO NOT EDIT.

//go:generate trilha gen

package main

import (
	"embed"

	trilha "github.com/emersonjoe/trilha"
	app "github.com/emersonjoe/trilha/otel/example/app"
	app_traco "github.com/emersonjoe/trilha/otel/example/app/traco"
)

//go:embed public
var publicFS embed.FS

// newApp builds the application. Tests can call it and use a.Handler().
func newApp() *trilha.App {
	cfg := trilha.ConfigFromEnv()
	cfg.Public = trilha.PublicFS(publicFS, "public")
	a := trilha.New(cfg)
	if err := app.Setup(a); err != nil {
		trilha.Fatal(err)
	}
	a.Register(trilha.Route{
		Pattern: "/",
		Page:    app.Page,
	})
	a.Register(trilha.Route{
		Pattern: "/traco",
		Methods: map[string]trilha.HandlerFunc{
			"GET": app_traco.GET,
		},
	})
	return a
}

func main() {
	trilha.Run(newApp())
}
